### ISSUE TITLE
经常发生的不知原因的错误

### ISSUE THREAD

**Issue by Anivie** [alibaba-cloud-toolkit/cosy#1]
似乎没有什么规律，不知道什么时候就会出现：
Cosy execution errororg.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: 管道正在被关闭。

java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: 管道正在被关闭。
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
	at com.alibabacloud.intellij.cosy.core.lsp.LanguageService.completion(LanguageService.java:106)
	at com.alibabacloud.intellij.cosy.core.lsp.LanguageService.lambda$completionWithDebouncer$0(LanguageService.java:75)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: 管道正在被关闭。
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:72)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.request(RemoteEndpoint.java:161)
	at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(EndpointProxy.java:91)
	at com.sun.proxy.$Proxy119.completion(Unknown Source)
	at com.alibabacloud.intellij.cosy.core.lsp.LanguageService.completion(LanguageService.java:105)
	... 6 more
Caused by: java.io.IOException: 管道正在被关闭。
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:69)
	... 10 more

**Comment by HaoboGu** [comment]
已修复，请更新至0.9.2-beta版本
