### ISSUE TITLE
初始化失败

### ISSUE THREAD

**Issue by gzpingtouge** [alibaba-cloud-toolkit/cosy#102]
java.lang.Throwable: Init Cosy language service error, reached maximum retry times (0)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:165)
	at com.alibabacloud.intellij.cosy.core.Cosy.startup(Cosy.java:156)
	at com.alibabacloud.intellij.cosy.core.Cosy$1.run(Cosy.java:111)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:962)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:472)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by zxdxjtu** [comment]
麻烦提供下cosy的日志：
Mac用户：~/.cosy/logs
Windows用户：C盘/用户/[用户名]/.cosy/logs

请问是什么插件版本
idea日志上面还有cosy相关的日志吗

**Comment by gzpingtouge** [comment]
[cosy.log](https://github.com/alibaba-cloud-toolkit/cosy/files/8973900/cosy.log)

插件版本：Alibaba Cloud AI Coding Assistant (Cosy)  0.10.2-b

**Comment by zxdxjtu** [comment]
麻烦试一下我们最新的0.10.3-beta版本呢，可以在插件市场里更新

**Comment by gzpingtouge** [comment]
更新到0.10.3-b后idea 沒有报错日志了， 但是代码示例以及参考文档都不能查询出结果

cosy日志：
``2022-06-24T15:27:24.184+0800	INFO	Checking update ...
2022-06-24T15:27:24.187+0800	INFO	System platform x86_64_windows
2022-06-24T15:27:25.431+0800	INFO	Skip update, current version: 0.2.10
2022-06-24T15:27:25.431+0800	INFO	Succeed to update Cosy binary
2022-06-24T15:27:25.465+0800	INFO	Skip update model, current version: 0.0.3
2022-06-24T15:27:25.465+0800	INFO	Succeed to update Cosy model
2022-06-24T15:27:25.478+0800	INFO	Inference environment checked, skip downloading
2022-06-24T15:27:25.478+0800	INFO	Succeed to update inference env
2022-06-24T15:27:25.889+0800	INFO	Checking update ...
2022-06-24T15:27:25.892+0800	INFO	System platform x86_64_windows
2022-06-24T15:27:25.937+0800	INFO	===== Starting cosy service =====
2022-06-24T15:27:25.952+0800	INFO	Checking update ...
2022-06-24T15:27:25.954+0800	WARN	Failed to get updating lock, skipping
2022-06-24T15:27:26.152+0800	INFO	===== Starting cosy service =====
2022-06-24T15:27:26.153+0800	INFO	Failed to get lock, exit
2022-06-24T15:27:27.125+0800	INFO	Skip update, current version: 0.2.10
2022-06-24T15:27:27.125+0800	INFO	Succeed to update Cosy binary
2022-06-24T15:27:27.161+0800	INFO	Skip update model, current version: 0.0.3
2022-06-24T15:27:27.161+0800	INFO	Succeed to update Cosy model
2022-06-24T15:27:27.175+0800	INFO	Inference environment checked, skip downloading
2022-06-24T15:27:27.175+0800	INFO	Succeed to update inference env
2022-06-24T15:27:27.363+0800	INFO	Preparing inference environment
2022-06-24T15:27:27.363+0800	INFO	Inference environment is ready
2022-06-24T15:27:27.363+0800	INFO	Starting local cosy inference service
2022-06-24T15:27:27.375+0800	INFO	Local inference service initialized

**Comment by zxdxjtu** [comment]
能试下把cosy进程kill掉，然后删除.cosy目录，重启idea吗？如果还是启动不起来的话，麻烦把.cosy/logs目录下的日志，包括cosy.log和cosylocal.log，还有idea日志中与cosy相关的部分，我们尽快排查
