### ISSUE TITLE
无所搜索

### ISSUE THREAD

**Issue by wangjxian** [alibaba-cloud-toolkit/cosy#103]
**Describe the bug（描述您遇到的问题）**
示例代码都不能搜索

**To Reproduce（复现步骤）**
搜索示例代码

**Screenshots（截图）**

<img width="626" alt="image" src="https://user-images.githubusercontent.com/43779826/176335015-574b9402-ea5b-45ba-b8b6-e98abe7c4a2c.png">

**System（本地系统）**
 - OS: macos
 - Cosy Version: 12.3.1

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by zxdxjtu** [comment]
麻烦告知一下cosy的版本号，以及确认下补全是否正常，cosy进程是否存在。
另外麻烦提供下日志信息：

cosy日志：
Mac用户：~/.cosy/logs
Windows用户：C盘/用户/[用户名]/.cosy/logs

idea日志：
工具栏：Help > Show log in Finder

**Comment by wangjxian** [comment]
2022-06-29 13:38:45,778 [  10649]   INFO - #c.a.i.c.c.Cosy - Retry for fetching .info for 1 times, 19 times left
2022-06-29 13:38:45,779 [  10650]   INFO - #c.a.i.c.c.w.CosyWebSocketClient - Cosy connect failed, cost 1 ms
2022-06-29 13:38:45,780 [  10651]   WARN - #c.a.i.c.c.Cosy - Connect to Cosy server error, try to kill process and restart
javax.websocket.DeploymentException: Deploying websocket encountered error
	at com.alibabacloud.intellij.cosy.core.websocket.CosyWebSocketClient.connect(CosyWebSocketClient.java:66)
	at com.alibabacloud.intellij.cosy.core.lsp.LanguageWebSocketService.connect(LanguageWebSocketService.java:69)
	at com.alibabacloud.intellij.cosy.core.Cosy.connectCosyServer(Cosy.java:260)
	at com.alibabacloud.intellij.cosy.core.Cosy.startCosy(Cosy.java:237)
	at com.alibabacloud.intellij.cosy.core.Cosy.connectCosyServer(Cosy.java:266)
	at com.alibabacloud.intellij.cosy.core.Cosy.startCosy(Cosy.java:237)
	at com.alibabacloud.intellij.cosy.core.Cosy.initCosyLanguageService(Cosy.java:217)
	at com.alibabacloud.intellij.cosy.core.Cosy.startup(Cosy.java:161)
	at com.alibabacloud.intellij.cosy.core.Cosy$1.run(Cosy.java:113)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by wangjxian** [comment]
<img width="451" alt="image" src="https://user-images.githubusercontent.com/43779826/176360377-f89db121-dc85-4603-90fa-aa059154b399.png">

**Comment by wangjxian** [comment]
[cosy.log](https://github.com/alibaba-cloud-toolkit/cosy/files/9007581/cosy.log)

**Comment by wangjxian** [comment]
[cosy-local.log](https://github.com/alibaba-cloud-toolkit/cosy/files/9007582/cosy-local.log)

**Comment by wangjxian** [comment]
[idea.log](https://github.com/alibaba-cloud-toolkit/cosy/files/9007587/idea.log)

**Comment by HaoboGu** [comment]
@wangjxian 你可以尝试一下，在本地hosts文件中添加一行
```
127.0.0.1 localhost
```
