### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Barsminto** [alibaba-cloud-toolkit/cosy#107]
com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.PsiJavaFileImpl
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getNode(StubBasedPsiElementBase.java:121)
	at com.intellij.psi.impl.source.PsiMethodImpl.getNode(PsiMethodImpl.java:250)
	at com.intellij.psi.impl.source.PsiMethodImpl.getNode(PsiMethodImpl.java:40)
	at com.intellij.psi.PsiInvalidElementAccessException.getPsiInvalidationTrace(PsiInvalidElementAccessException.java:98)
	at com.intellij.psi.PsiInvalidElementAccessException.<init>(PsiInvalidElementAccessException.java:61)
	at com.intellij.psi.PsiInvalidElementAccessException.<init>(PsiInvalidElementAccessException.java:33)
	at com.intellij.psi.util.PsiUtilCore.ensureValid(PsiUtilCore.java:478)
	at com.intellij.psi.impl.PsiClassImplUtil.skipInvalid(PsiClassImplUtil.java:401)
	at com.intellij.psi.impl.PsiClassImplUtil.access$200(PsiClassImplUtil.java:43)
	at com.intellij.psi.impl.PsiClassImplUtil$MemberCache.lambda$new$2(PsiClassImplUtil.java:361)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at one.util.streamex.AbstractStreamEx.forEach(AbstractStreamEx.java:352)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
	at one.util.streamex.StreamEx.toArray(StreamEx.java:871)
	at com.intellij.psi.impl.PsiClassImplUtil$MemberCache.lambda$new$3(PsiClassImplUtil.java:361)
	at com.intellij.util.containers.ConcurrentFactoryMap$2.create(ConcurrentFactoryMap.java:174)
	at com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:40)
	at com.intellij.psi.impl.PsiClassImplUtil$MemberCache.getAllMembers(PsiClassImplUtil.java:395)
	at com.intellij.psi.impl.PsiClassImplUtil.getAllByMap(PsiClassImplUtil.java:173)
	at com.intellij.psi.impl.PsiClassImplUtil.getAllMethods(PsiClassImplUtil.java:54)
	at com.intellij.psi.impl.source.PsiClassImpl.getAllMethods(PsiClassImpl.java:340)
	at com.alibabacloud.intellij.cosy.util.PsiUtils.getMethodsFromPsiClass(PsiUtils.java:88)
	at com.alibabacloud.intellij.cosy.linguist.util.CosyPsiUtils.findMethodsFieldsFromPsiTypeWhenDot(CosyPsiUtils.java:370)
	at com.alibabacloud.intellij.cosy.linguist.psi.model.CosyPsiJavaCodeReferenceElement.guessVariable(CosyPsiJavaCodeReferenceElement.java:152)
	at com.alibabacloud.intellij.cosy.linguist.psi.model.CosyPsiJavaCodeReferenceElement.parse(CosyPsiJavaCodeReferenceElement.java:122)
	at com.alibabacloud.intellij.cosy.linguist.psi.core.CosyPsiManager.guessCosyPsiElement(CosyPsiManager.java:91)
	at com.alibabacloud.intellij.cosy.linguist.psi.core.CosyPsiManager.convertToCosyPsiElement(CosyPsiManager.java:60)
	at com.alibabacloud.intellij.cosy.linguist.processor.CandidateAnalyzeProcessor$CosyRootComputer.lambda$convertCosyTreeWithTimeout$0(CandidateAnalyzeProcessor.java:224)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:920)
	at com.alibabacloud.intellij.cosy.linguist.processor.CandidateAnalyzeProcessor$CosyRootComputer.lambda$convertCosyTreeWithTimeout$1(CandidateAnalyzeProcessor.java:222)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:326)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by zxdxjtu** [comment]
您好，感谢反馈，我们会在下个版本修复这个问题。该问题不会影响插件使用，请您暂时忽略。
