### ISSUE TITLE
bug 无法使用

### ISSUE THREAD

**Issue by CWTakiku** [alibaba-cloud-toolkit/cosy#108]
**Describe the bug（描述您遇到的问题）**
无法使用

**To Reproduce（复现步骤）**

**Screenshots（截图）**
java.lang.IllegalStateException: JCEF is not supported in this env or failed to initialize
	at com.intellij.ui.jcef.JBCefApp.getInstance(JBCefApp.java:243)
	at com.intellij.ui.jcef.JBCefBrowserBase.lambda$new$3(JBCefBrowserBase.java:143)
	at com.intellij.util.ObjectUtils.notNull(ObjectUtils.java:127)
	at com.intellij.ui.jcef.JBCefBrowserBase.<init>(JBCefBrowserBase.java:143)
	at com.intellij.ui.jcef.JBCefBrowser.<init>(JBCefBrowser.java:178)
	at com.intellij.ui.jcef.JBCefBrowser.<init>(JBCefBrowser.java:147)
	at com.alibabacloud.intellij.cosy.ui.search.SearchResultPanel.createUIComponents(SearchResultPanel.java:121)
	at com.alibabacloud.intellij.cosy.ui.search.SearchResultPanel.$$$setupUI$$$(SearchResultPanel.java)
	at com.alibabacloud.intellij.cosy.ui.search.SearchResultPanel.<init>(SearchResultPanel.java:72)
	at com.alibabacloud.intellij.cosy.ui.search.SearchMainPanel.<init>(SearchMainPanel.java:218)
	at com.alibabacloud.intellij.cosy.ui.search.SearchToolWindowFactory.createToolWindowContent(SearchToolWindowFactory.java:58)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:524)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:503)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:1016)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:962)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow(ToolWindowManagerImpl.kt:665)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow$default(ToolWindowManagerImpl.kt:643)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activated$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:2027)
	at com.intellij.openapi.wm.impl.StripeButton.lambda$new$0(StripeButton.java:68)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:401)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6652)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at com.intellij.openapi.wm.impl.StripeButton.processMouseEvent(StripeButton.java:329)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:814)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**System（本地系统）**
 - OS: 
 - Cosy Version: 0.10.3.2-beta

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**
916379012@qq.com

**Comment by zxdxjtu** [comment]
您好，请问你是android studio吗？我们发现android studio不支持jcef，已经做了热修，麻烦下载后本地安装一下：
https://codeup-algo.oss-cn-hangzhou.aliyuncs.com/biz/cosy-intellij/hotfix/cosy-intellij-0.10.3.2-beta-jcef-hotfix.zip

**Comment by CWTakiku** [comment]
谢谢！但是我的代码智能补全没有，android studio 右下角没有cosy图标

**Comment by zxdxjtu** [comment]
麻烦提供下cosy和cosylocal的日志，

Mac用户：~/.cosy/logs
Windows用户：C盘/用户/[用户名]/.cosy/logs

**Comment by CWTakiku** [comment]
022-07-07T11:25:06.033+0800	WARN	Failed to get update lock before starts Cosy: context deadline exceeded
2022-07-07T11:25:06.034+0800	INFO	Preparing inference environment
2022-07-07T11:25:06.034+0800	INFO	Inference environment is ready
2022-07-07T11:25:06.034+0800	INFO	Starting local cosy inference service
2022-07-07T11:25:06.280+0800	INFO	Local inference service initialized
2022-07-07T11:26:44.179+0800	INFO	Checking update ...
2022-07-07T11:26:44.180+0800	WARN	Failed to get updating lock, skipping
2022-07-07T11:26:44.694+0800	INFO	Checking update ...
2022-07-07T11:26:44.695+0800	WARN	Failed to get updating lock, skipping
2022-07-07T11:26:44.902+0800	INFO	===== Starting cosy service =====
2022-07-07T11:26:45.313+0800	INFO	===== Starting cosy service =====
2022-07-07T11:26:45.315+0800	INFO	Failed to get lock, exit
2022-07-07T11:27:48.777+0800	INFO	Checking update ...
2022-07-07T11:27:48.778+0800	WARN	Failed to get updating lock, skipping
2022-07-07T11:27:48.995+0800	INFO	Checking update ...
2022-07-07T11:27:48.996+0800	WARN	Failed to get updating lock, skipping
2022-07-07T11:27:49.450+0800	INFO	===== Starting cosy service =====
2022-07-07T11:27:49.451+0800	INFO	Failed to get lock, exit
2022-07-07T11:27:49.762+0800	INFO	===== Starting cosy service =====
2022-07-07T11:27:49.763+0800	INFO	Failed to get lock, exit
2022-07-07T11:27:50.386+0800	INFO	Checking update ...
2022-07-07T11:27:50.388+0800	WARN	Failed to get updating lock, skipping
2022-07-07T11:27:50.561+0800	INFO	Checking update ...
2022-07-07T11:27:50.562+0800	WARN	Failed to get updating lock, skipping
2022-07-07T11:27:50.746+0800	INFO	Checking update ...
2022-07-07T11:27:50.747+0800	WARN	Failed to get updating lock, skipping
2022-07-07T11:27:51.232+0800	INFO	===== Starting cosy service =====
2022-07-07T11:27:51.233+0800	INFO	Failed to get lock, exit
2022-07-07T11:27:51.434+0800	INFO	Checking update ...
2022-07-07T11:27:51.435+0800	WARN	Failed to get updating lock, skipping
2022-07-07T11:27:51.583+0800	INFO	===== Starting cosy service =====
2022-07-07T11:27:51.584+0800	INFO	Failed to get lock, exit
2022-07-07T11:27:51.782+0800	INFO	Checking update ...
2022-07-07T11:27:51.783+0800	WARN	Failed to get updating lock, skipping
2022-07-07T11:27:52.322+0800	INFO	===== Starting cosy service =====




y_local::server: Inference model loaded
2022-07-14T01:27:15.438093Z  INFO cosy_local::server: Initializing inference service
2022-07-14T01:27:15.732111Z  INFO cosy_local::server: Inference service initialized
2022-07-14T01:27:15.732186Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:27:15.732212Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:27:15.732217Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:27:15.732222Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:27:15.732226Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:27:15.732227Z ERROR cosy_local::server: Quitting cosylocal because stdio is closed
2022-07-14T01:28:24.900514Z  INFO cosy_local::server: Inference model loaded
2022-07-14T01:28:24.984300Z  INFO cosy_local::server: Initializing inference service
2022-07-14T01:28:25.187389Z  INFO cosy_local::server: Inference service initialized
2022-07-14T01:28:25.187423Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:28:25.187434Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:28:25.187437Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:28:25.187441Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:28:25.187444Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:28:25.187445Z ERROR cosy_local::server: Quitting cosylocal because stdio is closed
2022-07-14T01:28:25.431966Z  INFO cosy_local::server: Inference model loaded
2022-07-14T01:28:25.502971Z  INFO cosy_local::server: Initializing inference service
2022-07-14T01:28:25.677810Z  INFO cosy_local::server: Inference service initialized
2022-07-14T01:28:25.677848Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:28:25.677859Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:28:25.677863Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:28:25.677867Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:28:25.677870Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:28:25.677871Z ERROR cosy_local::server: Quitting cosylocal because stdio is closed
2022-07-14T01:28:31.987786Z  INFO cosy_local::server: Inference model loaded
2022-07-14T01:28:32.065269Z  INFO cosy_local::server: Initializing inference service
2022-07-14T01:28:32.265975Z  INFO cosy_local::server: Inference service initialized
2022-07-14T01:28:32.266019Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:28:32.266032Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:28:32.266035Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:28:32.266039Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:28:32.266042Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:28:32.266043Z ERROR cosy_local::server: Quitting cosylocal because stdio is closed
2022-07-14T01:28:32.299258Z  INFO cosy_local::server: Inference model loaded
2022-07-14T01:28:32.372998Z  INFO cosy_local::server: Initializing inference service
2022-07-14T01:28:32.533234Z  INFO cosy_local::server: Inference service initialized
2022-07-14T01:28:32.533299Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:28:32.533313Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:28:32.533319Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:28:32.533323Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:28:32.533328Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:28:32.533329Z ERROR cosy_local::server: Quitting cosylocal because stdio is closed
2022-07-14T01:29:13.501306Z  INFO cosy_local::server: Inference model loaded
2022-07-14T01:29:13.586198Z  INFO cosy_local::server: Initializing inference service
2022-07-14T01:29:13.878488Z  INFO cosy_local::server: Inference service initialized
2022-07-14T01:29:13.878592Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:29:13.878620Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:29:13.878628Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:29:13.878637Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:29:13.878645Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:29:13.878648Z ERROR cosy_local::server: Quitting cosylocal because stdio is closed
2022-07-14T01:29:14.369350Z  INFO cosy_local::server: Inference model loaded
2022-07-14T01:29:14.480889Z  INFO cosy_local::server: Initializing inference service
2022-07-14T01:29:14.743176Z  INFO cosy_local::server: Inference service initialized
2022-07-14T01:29:14.743250Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:29:14.743273Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:29:14.743279Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:29:14.743284Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:29:14.743288Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:29:14.743290Z ERROR cosy_local::server: Quitting cosylocal because stdio is closed
2022-07-14T01:29:16.032879Z  INFO cosy_local::server: Inference model loaded
2022-07-14T01:29:16.119222Z  INFO cosy_local::server: Initializing inference service
2022-07-14T01:29:16.590777Z  INFO cosy_local::server: Inference service initialized
2022-07-14T01:29:16.590841Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:29:16.590859Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:29:16.590864Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:29:16.590869Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:29:16.590873Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:29:16.590875Z ERROR cosy_local::server: Quitting cosylocal because stdio is closed
2022-07-14T01:29:16.768943Z  INFO cosy_local::server: Inference model loaded
2022-07-14T01:29:16.864350Z  INFO cosy_local::server: Initializing inference service
2022-07-14T01:29:17.035635Z  INFO cosy_local::server: Inference service initialized
2022-07-14T01:29:17.035705Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:29:17.035720Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:29:17.035726Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:29:17.035730Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:29:17.035735Z ERROR cosy_local::server: Cannot handle message: EOF encountered in the middle of reading LSP headers
2022-07-14T01:29:17.035737Z ERROR cosy_local::server: Quitting cosylocal because stdio is closed
2022-07-14T01:29:18.917475Z  INFO cosy_local::server: Inference model loaded
2022-07-14T01:29:19.000224Z  INFO cosy_local::server: Initializing inference service
2022-07-14T01:29:19.229720Z  INFO cosy_local::server: Inference service initialized

**Comment by zxdxjtu** [comment]
麻烦试一下，把cosy进程杀死，把.cosy目录删除，重启下idea

**Comment by CWTakiku** [comment]
好了 谢谢！
