### ISSUE TITLE
代码文档搜索打开时，显示无可展示内容(Nothing to show)具体存在报错

### ISSUE THREAD

**Issue by hnwlxywns** [alibaba-cloud-toolkit/cosy#112]
**Describe the bug（描述您遇到的问题）**
java.lang.UnsatisfiedLinkError: no chrome_elf in java.library.path: [C:\Program Files\JetBrains\IntelliJ IDEA 2021.2.4\bin, C:\WINDOWS\Sun\Java\bin, C:\WINDOWS\system32, C:\WINDOWS, D:\Database\product\11.2\dbhome_1\bin, C:\ProgramData\Oracle\Java\javapath, C:\Windows\system32, C:\Windows, C:\Windows\System32\Wbem, C:\Windows\System32\WindowsPowerShell\v1.0\, C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common, C:\Program Files\TortoiseSVN\bin, D:\Program Files\apache-maven-3.3.9\bin, D:\Program Files\nodejs, D:\Program Files\nodejs\node_global, C:\WINDOWS\system32, C:\WINDOWS, C:\WINDOWS\System32\Wbem, C:\WINDOWS\System32\WindowsPowerShell\v1.0\, C:\Program Files\TortoiseGit\bin, C:\WINDOWS\System32\OpenSSH\, C:\Program Files\Java\jdk1.8.0_144\bin, C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\, C:\Program Files\Microsoft SQL Server\110\Tools\Binn\, C:\Program Files (x86)\Tesseract-OCR, D:\Program Files\OpenCV\opencv\build\x86\vc12\bin, D:\Program Files\OpenCV\opencv\build\x64\vc12\bin, D:\Program Files\OpenCV\opencv\build\java\x64\vc12\bin, C:\Program Files\Microsoft VS Code\bin, C:\Program Files\nodejs\, C:\ProgramData\chocolatey\bin, C:\Program Files\dotnet\, C:\Program Files (x86)\dotnet\, C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR, C:\WINDOWS\system32, C:\WINDOWS, C:\WINDOWS\System32\Wbem, C:\WINDOWS\System32\WindowsPowerShell\v1.0\, C:\WINDOWS\System32\OpenSSH\, c:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL, c:\Program Files\Intel\Intel(R) Management Engine Components\DAL, E:\Program Files (x86)\ffmpeg, C:\Program Files\Git\cmd, C:\Users\THINK\AppData\Local\Programs\Python\Python36\Scripts\, C:\Users\THINK\AppData\Local\Programs\Python\Python36\, C:\Users\THINK\AppData\Local\Microsoft\WindowsApps, ., C:\Program Files\Microsoft VS Code\bin, C:\Users\THINK\AppData\Roaming\npm, C:\Users\THINK\.dotnet\tools, C:\Users\THINK\AppData\Local\Microsoft\WindowsApps, C:\Program Files\JetBrains\IntelliJ IDEA 2021.2.2\bin, ., .]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at jcef/org.cef.SystemBootstrap$1.loadLibrary(SystemBootstrap.java:24)
	at jcef/org.cef.SystemBootstrap.loadLibrary(SystemBootstrap.java:36)
	at jcef/org.cef.CefApp.<init>(CefApp.java:153)
	at jcef/org.cef.CefApp.getInstance(CefApp.java:229)
	at jcef/org.cef.CefApp.getInstance(CefApp.java:216)
	at com.intellij.ui.jcef.JBCefApp.<init>(JBCefApp.java:195)
	at com.intellij.ui.jcef.JBCefApp$Holder.init(JBCefApp.java:271)
	at com.intellij.ui.jcef.JBCefApp$Holder.<clinit>(JBCefApp.java:251)
	at com.intellij.ui.jcef.JBCefApp.getInstance(JBCefApp.java:233)
	at com.intellij.ui.jcef.JBCefBrowserBase.lambda$new$3(JBCefBrowserBase.java:143)
	at com.intellij.util.ObjectUtils.notNull(ObjectUtils.java:127)
	at com.intellij.ui.jcef.JBCefBrowserBase.<init>(JBCefBrowserBase.java:143)
	at com.intellij.ui.jcef.JBCefBrowser.<init>(JBCefBrowser.java:178)
	at com.intellij.ui.jcef.JBCefBrowser.<init>(JBCefBrowser.java:147)
	at com.alibabacloud.intellij.cosy.ui.search.SearchResultPanel.createUIComponents(SearchResultPanel.java:121)
	at com.alibabacloud.intellij.cosy.ui.search.SearchResultPanel.$$$setupUI$$$(SearchResultPanel.java)
	at com.alibabacloud.intellij.cosy.ui.search.SearchResultPanel.<init>(SearchResultPanel.java:72)
	at com.alibabacloud.intellij.cosy.ui.search.SearchMainPanel.<init>(SearchMainPanel.java:218)
	at com.alibabacloud.intellij.cosy.ui.search.SearchToolWindowFactory.createToolWindowContent(SearchToolWindowFactory.java:58)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:524)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:503)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:1016)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:962)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow(ToolWindowManagerImpl.kt:665)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow$default(ToolWindowManagerImpl.kt:643)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activated$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:2027)
	at com.intellij.openapi.wm.impl.StripeButton.lambda$new$0(StripeButton.java:68)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:401)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6652)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at com.intellij.openapi.wm.impl.StripeButton.processMouseEvent(StripeButton.java:329)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:814)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**To Reproduce（复现步骤）**

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/8574812/181147024-9883d991-b554-4620-bc45-d2e7e119379a.png)

**System（本地系统）**
 - OS: win10
 - Cosy Version: 0.10.3.2-beta

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by zxdxjtu** [comment]
看起来好像是Windows系统中缺少chrome_elf.dll
麻烦手动安装下，然后重启idea试试呢？
https://windll.com/zh/dll/the-chromium-authors/chrome-elf

**Comment by hnwlxywns** [comment]
> 看起来好像是Windows系统中缺少chrome_elf.dll 麻烦手动安装下，然后重启idea试试呢？ https://windll.com/zh/dll/the-chromium-authors/chrome-elf

安装后，ieda用不了了，一打开工程，就idea软件就失去响应，只能卸载 这个插件了

**Comment by zxdxjtu** [comment]
能麻烦发一下安装dll后的日志吗？idea日志和cosy的日志
