### ISSUE TITLE
代码示例搜不到任何内容

### ISSUE THREAD

**Issue by sugarlesss** [alibaba-cloud-toolkit/cosy#114]
**Describe the bug（描述您遇到的问题）**
搜索框输入内容后搜索结果为空（即使是 cosy 推荐的几个搜索示例），并且 idea 底部就会提示 正在更新阿里云智能编码助手 Cosy。

**To Reproduce（复现步骤）**
安装 all in one 离线包之后，点击代码示例搜索，输入任意内容

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/49931320/181416125-c4402191-3fad-4ae4-a4da-26ebe44579b1.png)
![image](https://user-images.githubusercontent.com/49931320/181416265-769d5cf0-4909-4963-b434-fc51d5d5580b.png)

**System（本地系统）**
 - OS: Windows
 - Cosy Version: 0.10.3.2-beta-all-in-local

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**
[jaded@foxmail.com](mailto:jaded@foxmail.com)

**日志**
```
2022-07-28T11:40:45.503+0800	INFO	===== Starting cosy service =====
2022-07-28T11:40:45.512+0800	INFO	Preparing inference environment
2022-07-28T11:40:45.512+0800	INFO	Inference environment is ready
2022-07-28T11:40:45.512+0800	INFO	Starting local cosy inference service
2022-07-28T11:40:45.564+0800	INFO	Local inference service initialized
2022-07-28T11:41:10.673+0800	INFO	Checking update ...
2022-07-28T11:41:10.701+0800	INFO	System platform x86_64_windows
2022-07-28T11:41:13.571+0800	INFO	Skip update, current version: 0.2.10
2022-07-28T11:41:13.571+0800	INFO	Succeed to update Cosy binary
2022-07-28T11:41:13.662+0800	INFO	Skip update model, current version: 0.0.3
2022-07-28T11:41:13.662+0800	INFO	Succeed to update Cosy model
2022-07-28T11:41:13.733+0800	INFO	Inference environment checked, skip downloading
2022-07-28T11:41:13.733+0800	INFO	Succeed to update inference env
2022-07-28T11:41:15.529+0800	INFO	===== Starting cosy service =====
2022-07-28T11:41:15.541+0800	INFO	Preparing inference environment
2022-07-28T11:41:15.542+0800	INFO	Inference environment is ready
2022-07-28T11:41:15.542+0800	INFO	Starting local cosy inference service
2022-07-28T11:41:15.577+0800	INFO	Local inference service initialized
2022-07-28T11:41:51.736+0800	INFO	Checking update ...
2022-07-28T11:41:51.738+0800	INFO	System platform x86_64_windows
2022-07-28T11:41:52.319+0800	INFO	Skip update, current version: 0.2.10
2022-07-28T11:41:52.319+0800	INFO	Succeed to update Cosy binary
2022-07-28T11:41:52.349+0800	INFO	Skip update model, current version: 0.0.3
2022-07-28T11:41:52.349+0800	INFO	Succeed to update Cosy model
2022-07-28T11:41:52.371+0800	INFO	Inference environment checked, skip downloading
2022-07-28T11:41:52.371+0800	INFO	Succeed to update inference env
2022-07-28T11:41:52.679+0800	INFO	===== Starting cosy service =====
2022-07-28T11:41:52.680+0800	INFO	Preparing inference environment
2022-07-28T11:41:52.681+0800	INFO	Inference environment is ready
2022-07-28T11:41:52.681+0800	INFO	Starting local cosy inference service
2022-07-28T11:41:52.717+0800	INFO	Local inference service initialized
2022-07-28T11:42:09.061+0800	INFO	Checking update ...
2022-07-28T11:42:09.062+0800	INFO	System platform x86_64_windows
2022-07-28T11:42:09.359+0800	INFO	Skip update, current version: 0.2.10
2022-07-28T11:42:09.359+0800	INFO	Succeed to update Cosy binary
2022-07-28T11:42:09.389+0800	INFO	Skip update model, current version: 0.0.3
2022-07-28T11:42:09.389+0800	INFO	Succeed to update Cosy model
2022-07-28T11:42:09.404+0800	INFO	Inference environment checked, skip downloading
2022-07-28T11:42:09.404+0800	INFO	Succeed to update inference env
2022-07-28T11:42:09.647+0800	INFO	===== Starting cosy service =====
2022-07-28T11:42:09.648+0800	INFO	Preparing inference environment
2022-07-28T11:42:09.648+0800	INFO	Inference environment is ready
2022-07-28T11:42:09.648+0800	INFO	Starting local cosy inference service
2022-07-28T11:42:09.666+0800	INFO	Local inference service initialized
2022-07-28T11:45:11.475+0800	INFO	Checking update ...
2022-07-28T11:45:11.476+0800	INFO	System platform x86_64_windows
2022-07-28T11:45:12.612+0800	INFO	Skip update, current version: 0.2.10
2022-07-28T11:45:12.612+0800	INFO	Succeed to update Cosy binary
2022-07-28T11:45:12.644+0800	INFO	Skip update model, current version: 0.0.3
2022-07-28T11:45:12.644+0800	INFO	Succeed to update Cosy model
2022-07-28T11:45:12.660+0800	INFO	Inference environment checked, skip downloading
2022-07-28T11:45:12.660+0800	INFO	Succeed to update inference env
2022-07-28T11:45:12.974+0800	INFO	===== Starting cosy service =====
2022-07-28T11:45:12.978+0800	INFO	Preparing inference environment
2022-07-28T11:45:12.979+0800	INFO	Inference environment is ready
2022-07-28T11:45:12.980+0800	INFO	Starting local cosy inference service
2022-07-28T11:45:13.006+0800	INFO	Local inference service initialized
2022-07-28T11:45:29.735+0800	INFO	Checking update ...
2022-07-28T11:45:29.737+0800	INFO	System platform x86_64_windows
2022-07-28T11:45:30.004+0800	INFO	Skip update, current version: 0.2.10
2022-07-28T11:45:30.004+0800	INFO	Succeed to update Cosy binary
2022-07-28T11:45:30.034+0800	INFO	Skip update model, current version: 0.0.3
2022-07-28T11:45:30.034+0800	INFO	Succeed to update Cosy model
2022-07-28T11:45:30.047+0800	INFO	Inference environment checked, skip downloading
2022-07-28T11:45:30.047+0800	INFO	Succeed to update inference env
2022-07-28T11:45:30.319+0800	INFO	===== Starting cosy service =====
2022-07-28T11:45:30.320+0800	INFO	Preparing inference environment
2022-07-28T11:45:30.320+0800	INFO	Inference environment is ready
2022-07-28T11:45:30.320+0800	INFO	Starting local cosy inference service
2022-07-28T11:45:30.339+0800	INFO	Local inference service initialized
2022-07-28T11:47:17.576+0800	INFO	Checking update ...
2022-07-28T11:47:17.579+0800	INFO	System platform x86_64_windows
2022-07-28T11:47:17.867+0800	INFO	Skip update, current version: 0.2.10
2022-07-28T11:47:17.867+0800	INFO	Succeed to update Cosy binary
2022-07-28T11:47:17.894+0800	INFO	Skip update model, current version: 0.0.3
2022-07-28T11:47:17.894+0800	INFO	Succeed to update Cosy model
2022-07-28T11:47:17.909+0800	INFO	Inference environment checked, skip downloading
2022-07-28T11:47:17.909+0800	INFO	Succeed to update inference env
2022-07-28T11:47:18.153+0800	INFO	===== Starting cosy service =====
2022-07-28T11:47:18.155+0800	INFO	Preparing inference environment
2022-07-28T11:47:18.155+0800	INFO	Inference environment is ready
2022-07-28T11:47:18.155+0800	INFO	Starting local cosy inference service
2022-07-28T11:47:18.174+0800	INFO	Local inference service initialized
2022-07-28T11:48:38.041+0800	INFO	Checking update ...
2022-07-28T11:48:38.042+0800	INFO	System platform x86_64_windows
2022-07-28T11:48:38.328+0800	INFO	Skip update, current version: 0.2.10
2022-07-28T11:48:38.328+0800	INFO	Succeed to update Cosy binary
2022-07-28T11:48:38.360+0800	INFO	Skip update model, current version: 0.0.3
2022-07-28T11:48:38.360+0800	INFO	Succeed to update Cosy model
2022-07-28T11:48:38.380+0800	INFO	Inference environment checked, skip downloading
2022-07-28T11:48:38.381+0800	INFO	Succeed to update inference env
2022-07-28T11:48:38.757+0800	INFO	===== Starting cosy service =====
2022-07-28T11:48:38.758+0800	INFO	Preparing inference environment
2022-07-28T11:48:38.758+0800	INFO	Inference environment is ready
2022-07-28T11:48:38.758+0800	INFO	Starting local cosy inference service
2022-07-28T11:48:38.783+0800	INFO	Local inference service initialized
2022-07-28T11:50:51.927+0800	INFO	Checking update ...
2022-07-28T11:50:51.930+0800	INFO	System platform x86_64_windows
2022-07-28T11:50:52.296+0800	INFO	Skip update, current version: 0.2.10
2022-07-28T11:50:52.296+0800	INFO	Succeed to update Cosy binary
2022-07-28T11:50:52.337+0800	INFO	Skip update model, current version: 0.0.3
2022-07-28T11:50:52.337+0800	INFO	Succeed to update Cosy model
2022-07-28T11:50:52.352+0800	INFO	Inference environment checked, skip downloading
2022-07-28T11:50:52.352+0800	INFO	Succeed to update inference env
2022-07-28T11:50:52.693+0800	INFO	===== Starting cosy service =====
2022-07-28T11:50:52.695+0800	INFO	Preparing inference environment
2022-07-28T11:50:52.695+0800	INFO	Inference environment is ready
2022-07-28T11:50:52.695+0800	INFO	Starting local cosy inference service
2022-07-28T11:50:52.714+0800	INFO	Local inference service initialized
```

**Comment by sugarlesss** [comment]
每次搜索，idea 底部都会提示 正在更新阿里云智能编码助手 Cosy，但是搜不出来任何内容。

看了一下 Cosy 官网的 FAQ，已经按照相关步骤排查过。

1、ping codeup.cn-hangzhou.aliyuncs.com 正常
2、本地系统时间正常
3、日志文件 cosy.log，看日志也没有 ERROR，Cosy 进程看起来也是正常的

**Comment by HaoboGu** [comment]
能否看一下`idea.log`里面有没有相关的报错呢？

`idea.log`所在文件夹可以从此打开：
<img width="413" alt="image" src="https://user-images.githubusercontent.com/8640918/181433210-df1f93cf-169e-4190-94ff-cb00b4f9e401.png">

**Comment by sugarlesss** [comment]
> 能否看一下`idea.log`里面有没有相关的报错呢？
> 
> `idea.log`所在文件夹可以从此打开： <img alt="image" width="413" src="https://user-images.githubusercontent.com/8640918/181433210-df1f93cf-169e-4190-94ff-cb00b4f9e401.png">

日志如下：
```
2022-07-28 14:15:57,132 [9342362]   INFO - #c.a.i.c.c.BinaryManager - checking cosy updating.
2022-07-28 14:15:57,229 [9342459]   WARN - #c.a.i.c.c.BinaryManager - local binary version is equal to plugin internal version, checking signature
2022-07-28 14:15:58,516 [9343746]   INFO - #c.a.i.c.c.BinaryManager - calculate Cosy binary signature. cost:38
2022-07-28 14:15:58,531 [9343761]   INFO - #c.a.i.c.c.BinaryUpdater - wait for updating
2022-07-28 14:15:59,109 [9344339]   INFO - #c.a.i.c.c.BinaryUpdater - process output:
2022-07-28 14:15:59,109 [9344339]   INFO - #c.a.i.c.c.Cosy - cosy home dir C:\Users\22405\.cosy
2022-07-28 14:15:59,109 [9344339]   INFO - #c.a.i.c.c.Cosy - .info not exist, start to create Cosy process
2022-07-28 14:15:59,110 [9344340]   INFO - #c.a.i.c.c.BinaryRunner - Windows platform add 'cmd /c' to detach
2022-07-28 14:15:59,121 [9344351]   INFO - #c.a.i.c.c.Cosy - cosy home dir C:\Users\22405\.cosy
2022-07-28 14:15:59,122 [9344352]   INFO - #c.a.i.c.c.Cosy - .info file not exist, wait 100ms and retry
2022-07-28 14:15:59,427 [9344657]   INFO - #c.a.i.c.u.ProcessReader - panic: runtime error: index out of range [3] with length 0 [recovered]
2022-07-28 14:15:59,427 [9344657]   INFO - #c.a.i.c.u.ProcessReader - 	panic: 
2022-07-28 14:15:59,427 [9344657]   INFO - #c.a.i.c.u.ProcessReader - == Recovering from initIndex crash ==
2022-07-28 14:15:59,427 [9344657]   INFO - #c.a.i.c.u.ProcessReader - File Info: [ID: 137, Size: 225137, Zeros: 225137]
2022-07-28 14:15:59,427 [9344657]   INFO - #c.a.i.c.u.ProcessReader - isEnrypted: false checksumLen: 0 checksum:  indexLen: 0 index: [] 
2022-07-28 14:15:59,427 [9344657]   INFO - #c.a.i.c.u.ProcessReader - == Recovered ==
2022-07-28 14:15:59,427 [9344657]   INFO - #c.a.i.c.u.ProcessReader - 
2022-07-28 14:15:59,427 [9344657]   INFO - #c.a.i.c.u.ProcessReader - 
2022-07-28 14:15:59,427 [9344657]   INFO - #c.a.i.c.u.ProcessReader - goroutine 66 [running]:
2022-07-28 14:15:59,427 [9344657]   INFO - #c.a.i.c.u.ProcessReader - github.com/dgraph-io/badger/v3/table.(*Table).initBiggestAndSmallest.func1.1()
2022-07-28 14:15:59,427 [9344657]   INFO - #c.a.i.c.u.ProcessReader - 	github.com/dgraph-io/badger/v3@v3.2103.2/table/table.go:351 +0xa8
2022-07-28 14:15:59,427 [9344657]   INFO - #c.a.i.c.u.ProcessReader - github.com/dgraph-io/badger/v3/table.(*Table).initBiggestAndSmallest.func1()
2022-07-28 14:15:59,427 [9344657]   INFO - #c.a.i.c.u.ProcessReader - 	github.com/dgraph-io/badger/v3@v3.2103.2/table/table.go:397 +0xc2
2022-07-28 14:15:59,427 [9344657]   INFO - #c.a.i.c.u.ProcessReader - panic({0xcf0260, 0xc0000a20a8})
2022-07-28 14:15:59,427 [9344657]   INFO - #c.a.i.c.u.ProcessReader - 	runtime/panic.go:838 +0x207
2022-07-28 14:15:59,427 [9344657]   INFO - #c.a.i.c.u.ProcessReader - github.com/google/flatbuffers/go.GetUint32(...)
2022-07-28 14:15:59,428 [9344658]   INFO - #c.a.i.c.u.ProcessReader - 	github.com/google/flatbuffers@v2.0.6+incompatible/go/encode.go:47
2022-07-28 14:15:59,428 [9344658]   INFO - #c.a.i.c.u.ProcessReader - github.com/google/flatbuffers/go.GetUOffsetT(...)
2022-07-28 14:15:59,428 [9344658]   INFO - #c.a.i.c.u.ProcessReader - 	github.com/google/flatbuffers@v2.0.6+incompatible/go/encode.go:121
2022-07-28 14:15:59,428 [9344658]   INFO - #c.a.i.c.u.ProcessReader - github.com/dgraph-io/badger/v3/fb.GetRootAsTableIndex(...)
2022-07-28 14:15:59,428 [9344658]   INFO - #c.a.i.c.u.ProcessReader - 	github.com/dgraph-io/badger/v3@v3.2103.2/fb/TableIndex.go:14
2022-07-28 14:15:59,428 [9344658]   INFO - #c.a.i.c.u.ProcessReader - github.com/dgraph-io/badger/v3/table.(*Table).readTableIndex(0xc000148180)
2022-07-28 14:15:59,428 [9344658]   INFO - #c.a.i.c.u.ProcessReader - 	github.com/dgraph-io/badger/v3@v3.2103.2/table/table.go:707 +0x15e
2022-07-28 14:15:59,428 [9344658]   INFO - #c.a.i.c.u.ProcessReader - github.com/dgraph-io/badger/v3/table.(*Table).initIndex(0xc000148180)
2022-07-28 14:15:59,428 [9344658]   INFO - #c.a.i.c.u.ProcessReader - 	github.com/dgraph-io/badger/v3@v3.2103.2/table/table.go:462 +0x196
2022-07-28 14:15:59,428 [9344658]   INFO - #c.a.i.c.u.ProcessReader - github.com/dgraph-io/badger/v3/table.(*Table).initBiggestAndSmallest(0xc000148180)
2022-07-28 14:15:59,428 [9344658]   INFO - #c.a.i.c.u.ProcessReader - 	github.com/dgraph-io/badger/v3@v3.2103.2/table/table.go:401 +0x7f
2022-07-28 14:15:59,428 [9344658]   INFO - #c.a.i.c.u.ProcessReader - github.com/dgraph-io/badger/v3/table.OpenTable(0xc000096700, {0x0, 0x1, 0x200000, 0x0, 0x0, 0x3f847ae147ae147b, 0x1000, 0x0, 0x1, ...})
2022-07-28 14:15:59,428 [9344658]   INFO - #c.a.i.c.u.ProcessReader - 	github.com/dgraph-io/badger/v3@v3.2103.2/table/table.go:308 +0x272
2022-07-28 14:15:59,428 [9344658]   INFO - #c.a.i.c.u.ProcessReader - github.com/dgraph-io/badger/v3.newLevelsController.func1({0xc0005ac240, 0x29}, {0x0?, 0x0?, 0x0?})
2022-07-28 14:15:59,428 [9344658]   INFO - #c.a.i.c.u.ProcessReader - 	github.com/dgraph-io/badger/v3@v3.2103.2/levels.go:150 +0x1f9
2022-07-28 14:15:59,428 [9344658]   INFO - #c.a.i.c.u.ProcessReader - created by github.com/dgraph-io/badger/v3.newLevelsController
2022-07-28 14:15:59,428 [9344658]   INFO - #c.a.i.c.u.ProcessReader - 	github.com/dgraph-io/badger/v3@v3.2103.2/levels.go:129 +0x585
2022-07-28 14:15:59,623 [9344853]   INFO - #c.a.i.c.c.Cosy - Retry for fetching .info for 1 times, 19 times left
2022-07-28 14:15:59,623 [9344853]   INFO - #c.a.i.c.c.Cosy - .info file not exist, wait 100ms and retry
2022-07-28 14:16:00,126 [9345356]   INFO - #c.a.i.c.c.Cosy - Retry for fetching .info for 2 times, 18 times left
2022-07-28 14:16:00,126 [9345356]   INFO - #c.a.i.c.c.Cosy - .info file not exist, wait 100ms and retry
2022-07-28 14:16:00,628 [9345858]   INFO - #c.a.i.c.c.Cosy - Retry for fetching .info for 3 times, 17 times left
2022-07-28 14:16:00,628 [9345858]   INFO - #c.a.i.c.c.Cosy - .info file not exist, wait 100ms and retry
2022-07-28 14:16:01,129 [9346359]   INFO - #c.a.i.c.c.Cosy - Retry for fetching .info for 4 times, 16 times left
2022-07-28 14:16:01,130 [9346360]   INFO - #c.a.i.c.c.Cosy - .info file not exist, wait 100ms and retry
2022-07-28 14:16:01,644 [9346874]   INFO - #c.a.i.c.c.Cosy - Retry for fetching .info for 5 times, 15 times left
2022-07-28 14:16:01,644 [9346874]   INFO - #c.a.i.c.c.Cosy - .info file not exist, wait 100ms and retry
2022-07-28 14:16:02,157 [9347387]   INFO - #c.a.i.c.c.Cosy - Retry for fetching .info for 6 times, 14 times left
2022-07-28 14:16:02,157 [9347387]   INFO - #c.a.i.c.c.Cosy - .info file not exist, wait 100ms and retry
2022-07-28 14:16:02,657 [9347887]   INFO - #c.a.i.c.c.Cosy - Retry for fetching .info for 7 times, 13 times left
2022-07-28 14:16:02,657 [9347887]   INFO - #c.a.i.c.c.Cosy - .info file not exist, wait 100ms and retry
2022-07-28 14:16:03,160 [9348390]   INFO - #c.a.i.c.c.Cosy - Retry for fetching .info for 8 times, 12 times left
2022-07-28 14:16:03,160 [9348390]   INFO - #c.a.i.c.c.Cosy - .info file not exist, wait 100ms and retry
2022-07-28 14:16:03,672 [9348902]   INFO - #c.a.i.c.c.Cosy - Retry for fetching .info for 9 times, 11 times left
2022-07-28 14:16:03,672 [9348902]   INFO - #c.a.i.c.c.Cosy - .info file not exist, wait 100ms and retry
2022-07-28 14:16:04,185 [9349415]   INFO - #c.a.i.c.c.Cosy - Retry for fetching .info for 10 times, 10 times left
2022-07-28 14:16:04,185 [9349415]   INFO - #c.a.i.c.c.Cosy - .info file not exist, wait 100ms and retry
2022-07-28 14:16:04,697 [9349927]   INFO - #c.a.i.c.c.Cosy - Retry for fetching .info for 11 times, 9 times left
2022-07-28 14:16:04,698 [9349928]   INFO - #c.a.i.c.c.Cosy - .info file not exist, wait 100ms and retry
2022-07-28 14:16:05,212 [9350442]   INFO - #c.a.i.c.c.Cosy - Retry for fetching .info for 12 times, 8 times left
2022-07-28 14:16:05,212 [9350442]   INFO - #c.a.i.c.c.Cosy - .info file not exist, wait 100ms and retry
2022-07-28 14:16:05,827 [9351057]   INFO - #c.a.i.c.c.Cosy - Retry for fetching .info for 13 times, 7 times left
2022-07-28 14:16:05,827 [9351057]   INFO - #c.a.i.c.c.Cosy - .info file not exist, wait 100ms and retry
2022-07-28 14:16:06,342 [9351572]   INFO - #c.a.i.c.c.Cosy - Retry for fetching .info for 14 times, 6 times left
2022-07-28 14:16:06,342 [9351572]   INFO - #c.a.i.c.c.Cosy - .info file not exist, wait 100ms and retry
2022-07-28 14:16:06,859 [9352089]   INFO - #c.a.i.c.c.Cosy - Retry for fetching .info for 15 times, 5 times left
2022-07-28 14:16:06,859 [9352089]   INFO - #c.a.i.c.c.Cosy - .info file not exist, wait 100ms and retry
2022-07-28 14:16:07,372 [9352602]   INFO - #c.a.i.c.c.Cosy - Retry for fetching .info for 16 times, 4 times left
2022-07-28 14:16:07,372 [9352602]   INFO - #c.a.i.c.c.Cosy - .info file not exist, wait 100ms and retry
2022-07-28 14:16:07,873 [9353103]   INFO - #c.a.i.c.c.Cosy - Retry for fetching .info for 17 times, 3 times left
2022-07-28 14:16:07,873 [9353103]   INFO - #c.a.i.c.c.Cosy - .info file not exist, wait 100ms and retry
2022-07-28 14:16:08,374 [9353604]   INFO - #c.a.i.c.c.Cosy - Retry for fetching .info for 18 times, 2 times left
2022-07-28 14:16:08,375 [9353605]   INFO - #c.a.i.c.c.Cosy - .info file not exist, wait 100ms and retry
2022-07-28 14:16:08,887 [9354117]   INFO - #c.a.i.c.c.Cosy - Retry for fetching .info for 19 times, 1 times left
2022-07-28 14:16:08,887 [9354117]   INFO - #c.a.i.c.c.Cosy - .info file not exist, wait 100ms and retry
2022-07-28 14:16:09,402 [9354632]   INFO - #c.a.i.c.c.Cosy - Retry for fetching .info for 20 times, 0 times left
2022-07-28 14:16:09,402 [9354632]   WARN - #c.a.i.c.c.Cosy - Cannot read from .info, connect to Cosy server failed
2022-07-28 14:16:09,402 [9354632]   WARN - #c.a.i.c.c.Cosy - Cosy init failed
2022-07-28 14:16:09,402 [9354632]   INFO - #c.a.i.c.c.Cosy - succeed to startup cosy
```

有一个 `Cannot read from .info, connect to Cosy server failed` 的错误

**Comment by HaoboGu** [comment]
这个报错可能是因为db初始化有问题，可以尝试按照以下步骤修复：
1. 关掉IDE，并且杀掉cosy.exe进程
2. 把`[用户路径]/.cosy/tmp`删掉
3. 重启IDE，等待Cosy初始化
4. 如果依然有问题，可以尝试把`[用户路径]/.cosy`完全删掉再重试

我们目前遇到的这个case通过这个步骤一般都能解决。

这个报错是因为Cosy依赖的db有一些bug导致的，我们已经在推动他们修复，在他们完成修复之后我们会第一时间更新

**Comment by sugarlesss** [comment]
解决了，非常感谢 :-) 

期待早日修复

**Comment by sugarlesss** [comment]
> 

解决了，非常感谢 :-)

期待早日修复

**Comment by HaoboGu** [comment]
使用愉快~ :D
