### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by darkjune** [alibaba-cloud-toolkit/cosy#138]
**Describe the bug（描述您遇到的问题）**
启动idea后提示有错误

WebSocket encountered error

java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: Broken pipe
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:327)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:262)
	at org.apache.tomcat.websocket.WsSession.sendCloseMessage(WsSession.java:816)
	at org.apache.tomcat.websocket.WsSession.onClose(WsSession.java:739)
	at org.apache.tomcat.websocket.WsFrameBase.processDataControl(WsFrameBase.java:367)
	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:296)
	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
	at org.apache.tomcat.websocket.WsFrameClient.processSocketRead(WsFrameClient.java:95)
	at org.apache.tomcat.websocket.WsFrameClient.resumeProcessing(WsFrameClient.java:212)
	at org.apache.tomcat.websocket.WsFrameClient.access$500(WsFrameClient.java:31)
	at org.apache.tomcat.websocket.WsFrameClient$WsFrameClientCompletionHandler.doResumeProcessing(WsFrameClient.java:189)
	at org.apache.tomcat.websocket.WsFrameClient$WsFrameClientCompletionHandler.completed(WsFrameClient.java:163)
	at org.apache.tomcat.websocket.WsFrameClient$WsFrameClientCompletionHandler.completed(WsFrameClient.java:148)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishRead(UnixAsynchronousSocketChannelImpl.java:447)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:195)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:217)
	at java.base/sun.nio.ch.KQueuePort$EventHandlerTask.run(KQueuePort.java:312)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Broken pipe
	at java.base/sun.nio.ch.CompletedFuture.get(CompletedFuture.java:78)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplClient.doWrite(WsRemoteEndpointImplClient.java:62)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase$OutputBufferSendHandler.write(WsRemoteEndpointImplBase.java:952)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase$OutputBufferSendHandler.onResult(WsRemoteEndpointImplBase.java:967)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplClient.doWrite(WsRemoteEndpointImplClient.java:68)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase$OutputBufferSendHandler.write(WsRemoteEndpointImplBase.java:909)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.writeMessagePart(WsRemoteEndpointImplBase.java:509)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:314)
	... 21 more
Caused by: java.io.IOException: Broken pipe
	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:62)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:132)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:97)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:60)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.implWrite(UnixAsynchronousSocketChannelImpl.java:713)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.write(AsynchronousSocketChannelImpl.java:382)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.write(AsynchronousSocketChannelImpl.java:387)
	at org.apache.tomcat.websocket.AsyncChannelWrapperNonSecure.write(AsyncChannelWrapperNonSecure.java:58)
	... 28 more

**To Reproduce（复现步骤）**
idea启动
idea版本  2022.2.3 (Ultimate Edition)

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/3335076/204488279-8b74c00d-c557-41c9-846b-e1307af69828.png)

**System（本地系统）**
 - OS: MacOS Monterey  12.4
 - Cosy Version: 

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by zxdxjtu** [comment]
cosy客户端和cosy本地服务器的websocket链接断了，麻烦看下是不是本地有什么软件或者安全程序做了这个操作。也可以删除cosy进程，清空~/.cosy目录，然后重启idea再看看
