### ISSUE TITLE
Alibaba Cloud AI Coding Assistant搜索无效

### ISSUE THREAD

**Issue by huangsong2888** [alibaba-cloud-toolkit/cosy#202]
IntelliJ IDEA Community Edition 2023.1.1 安装好Alibaba Cloud AI Coding Assistant后搜索不生效。

![image](https://github.com/alibaba-cloud-toolkit/cosy/assets/83409331/150fa716-9a65-49ea-94c2-3ba40da472e0)

![image](https://github.com/alibaba-cloud-toolkit/cosy/assets/83409331/63472d7b-cbe5-4a4e-af4d-aefb9299fb07)

**Comment by zxdxjtu** [comment]
补全可以吗？看日志主要是补全模型没有下载成功，不知道网络是否能够联通aliyun oss？如果网络没有被限制的话，建议尝试下删除cosy进程，删除~/.cosy目录，重启IDE，如果还是不行的话，麻烦发送下完整的cosy.log文件

**Comment by huangsong2888** [comment]
补全也不行，日志如下

[cosy.log](https://github.com/alibaba-cloud-toolkit/cosy/files/12492296/cosy.log)

**Comment by zxdxjtu** [comment]
是公司内网环境吗？看起来是网络不行，cosy的模型环境没有下载成功，cosy没有成功启动。如果网络没有被限制的话，建议尝试下删除cosy进程，删除~/.cosy目录，重启IDE。
如果网络还是不行的话，可以尝试all-in-one版本，cosy会把一些模型文件提前打包到插件包里。
https://toolkit.aliyun.com/idea/cosy-intellij-beta-latest-all-in-one.zip

**Comment by huangsong2888** [comment]
使用all-in-one版本还是不太行，日志如下
[cosy.log](https://github.com/alibaba-cloud-toolkit/cosy/files/12494066/cosy.log)

**Comment by huangsong2888** [comment]
每次重启IDEA会有错误
java.lang.Throwable: invalid config content:null
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.alibabacloud.intellij.cosy.core.BinaryManager.getVersionString(BinaryManager.java:328)
	at com.alibabacloud.intellij.cosy.core.BinaryManager.checkBinaryVersion(BinaryManager.java:157)
	at com.alibabacloud.intellij.cosy.core.BinaryManager.checkCosy(BinaryManager.java:81)
	at com.alibabacloud.intellij.cosy.core.BinaryManager.checkCosy(BinaryManager.java:58)
	at com.alibabacloud.intellij.cosy.CosyLoader.lambda$componentsInitialized$0(CosyLoader.java:29)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by huangsong2888** [comment]
java.lang.Throwable: invalid config content:null
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.alibabacloud.intellij.cosy.core.BinaryManager.getVersionString(BinaryManager.java:328)
	at com.alibabacloud.intellij.cosy.core.BinaryManager.checkBinaryVersion(BinaryManager.java:157)
	at com.alibabacloud.intellij.cosy.core.BinaryManager.checkCosy(BinaryManager.java:81)
	at com.alibabacloud.intellij.cosy.core.BinaryManager.checkCosy(BinaryManager.java:58)
	at com.alibabacloud.intellij.cosy.core.Cosy$1.run(Cosy.java:125)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by liulhdarks** [comment]
麻烦看一下操作系统的时间有没有滞后或者超前？

**Comment by huangsong2888** [comment]
没有
