### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by M1NGc** [alibaba-cloud-toolkit/cosy#33]
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.intellij.psi.impl.ResolveScopeManager because container is already disposed (container=Project(name=heifengshan, containerState=DISPOSE_COMPLETED, componentStore=C:\zqykj\code\heifengshan) (disposed))
	at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:43)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:612)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:573)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.intellij.psi.impl.ResolveScopeManager.getInstance(ResolveScopeManager.java:24)
	at com.intellij.psi.impl.ResolveScopeManager.getElementResolveScope(ResolveScopeManager.java:36)
	at com.intellij.psi.impl.PsiElementBase.getResolveScope(PsiElementBase.java:183)
	at com.intellij.psi.impl.PsiClassImplUtil.getMap(PsiClassImplUtil.java:185)
	at com.intellij.psi.impl.PsiClassImplUtil.getAllByMap(PsiClassImplUtil.java:169)
	at com.intellij.psi.impl.PsiClassImplUtil.getAllMethods(PsiClassImplUtil.java:55)
	at com.intellij.psi.impl.compiled.ClsClassImpl.getAllMethods(ClsClassImpl.java:242)
	at com.alibabacloud.intellij.cosy.util.PsiUtils.getMethodsFromPsiClass(PsiUtils.java:88)
	at com.alibabacloud.intellij.cosy.linguist.util.CosyPsiUtils.findMethodsFieldsFroPsiTypeWhenDot(CosyPsiUtils.java:362)
	at com.alibabacloud.intellij.cosy.linguist.psi.model.CosyPsiJavaCodeReferenceElement.tacklePsiClass(CosyPsiJavaCodeReferenceElement.java:139)
	at com.alibabacloud.intellij.cosy.linguist.psi.model.CosyPsiJavaCodeReferenceElement.parse(CosyPsiJavaCodeReferenceElement.java:100)
	at com.alibabacloud.intellij.cosy.linguist.psi.core.CosyPsiManager.guessCosyPsiElement(CosyPsiManager.java:84)
	at com.alibabacloud.intellij.cosy.linguist.psi.core.CosyPsiManager.convertToCosyPsiElement(CosyPsiManager.java:59)
	at com.alibabacloud.intellij.cosy.linguist.processor.CandidateAnalyzeProcessor$1$1.lambda$convertCosyTreeWithTimeout$0(CandidateAnalyzeProcessor.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:841)
	at com.alibabacloud.intellij.cosy.linguist.processor.CandidateAnalyzeProcessor$1$1.lambda$convertCosyTreeWithTimeout$1(CandidateAnalyzeProcessor.java:140)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:296)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by effynku** [comment]
你好～感谢你的反馈(｡･ω･｡)ﾉ
这段报错的成因是：在工程关闭的时候，有一些补全语法处理有点滞后还在运行；虽然这个disposed提前在调用的时候做了判断，但是语法处理是异步的。
经过我们的排查和尝试，目前这个问题还没有找到很好的规避方法。但即使日志里出现了这个error日志，也不会影响插件的正常使用。我们也会继续尝试解决和优化这个问题的(｡･ω･｡)ﾉ
