### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ScmTble** [alibaba-cloud-toolkit/cosy#52]
**Describe the bug（描述您遇到的问题）**
Cosy进程不存在，无法使用补全

**To Reproduce（复现步骤）**

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/56188521/156709164-7dc47e56-42e2-4ce0-9d80-9a947b9ee469.png)

**日志**
2022-03-04T13:59:46.644+0800	INFO	System platform x86_64_windows
2022-03-04T13:59:47.134+0800	INFO	Skip update, current version: 0.2.1
2022-03-04T13:59:47.134+0800	INFO	Succeed to update Cosy binary
2022-03-04T13:59:47.135+0800	WARN	Failed to load model config
2022-03-04T13:59:47.176+0800	INFO	Updating model to 0.0.3
2022-03-04T14:01:03.365+0800	INFO	Succeed to update Cosy model
2022-03-04T14:01:03.377+0800	INFO	Inference environment checked, skip downloading
2022-03-04T14:01:03.377+0800	INFO	Succeed to update inference env
2022-03-04T14:01:03.552+0800	INFO	Preparing inference environment
2022-03-04T14:01:03.552+0800	INFO	Inference environment is ready
2022-03-04T14:01:03.552+0800	INFO	Starting local cosy inference service
2022-03-04T14:01:03.565+0800	INFO	Local inference service initialized
2022-03-04T14:01:03.595+0800	ERROR	Failed to write lock info
2022-03-04T14:01:15.289+0800	INFO	System platform x86_64_windows
2022-03-04T14:01:15.343+0800	WARN	Failed to get updating lock, skipping
2022-03-04T14:01:15.502+0800	INFO	Preparing inference environment
2022-03-04T14:01:15.503+0800	INFO	Inference environment is ready
2022-03-04T14:01:15.503+0800	INFO	Starting local cosy inference service
2022-03-04T14:01:15.512+0800	INFO	Local inference service initialized
2022-03-04T14:01:15.524+0800	ERROR	Failed to write lock info
2022-03-04T14:01:15.755+0800	INFO	Skip update, current version: 0.2.1
2022-03-04T14:01:15.755+0800	INFO	Succeed to update Cosy binary
2022-03-04T14:01:15.800+0800	INFO	Skip update model, current version: 0.0.3
2022-03-04T14:01:15.800+0800	INFO	Succeed to update Cosy model
2022-03-04T14:01:15.812+0800	INFO	Inference environment checked, skip downloading
2022-03-04T14:01:15.812+0800	INFO	Succeed to update inference env
2022-03-04T14:01:15.979+0800	INFO	Preparing inference environment
2022-03-04T14:01:15.980+0800	INFO	Inference environment is ready
2022-03-04T14:01:15.980+0800	INFO	Starting local cosy inference service
2022-03-04T14:01:15.991+0800	INFO	Local inference service initialized
2022-03-04T14:01:16.009+0800	ERROR	Failed to write lock info
2022-03-04T14:01:19.947+0800	INFO	System platform x86_64_windows
2022-03-04T14:01:20.333+0800	WARN	Failed to get updating lock, skipping
2022-03-04T14:01:20.393+0800	INFO	Skip update, current version: 0.2.1
2022-03-04T14:01:20.393+0800	INFO	Succeed to update Cosy binary
2022-03-04T14:01:20.434+0800	INFO	Skip update model, current version: 0.0.3
2022-03-04T14:01:20.434+0800	INFO	Succeed to update Cosy model
2022-03-04T14:01:20.447+0800	INFO	Inference environment checked, skip downloading
2022-03-04T14:01:20.447+0800	INFO	Succeed to update inference env
2022-03-04T14:01:20.499+0800	INFO	Preparing inference environment
2022-03-04T14:01:20.499+0800	INFO	Inference environment is ready
2022-03-04T14:01:20.499+0800	INFO	Starting local cosy inference service
2022-03-04T14:01:20.509+0800	INFO	Local inference service initialized
2022-03-04T14:01:20.519+0800	ERROR	Failed to write lock info
2022-03-04T14:01:20.638+0800	INFO	Preparing inference environment
2022-03-04T14:01:20.638+0800	INFO	Inference environment is ready
2022-03-04T14:01:20.638+0800	INFO	Starting local cosy inference service
2022-03-04T14:01:20.654+0800	INFO	Local inference service initialized
2022-03-04T14:01:20.669+0800	ERROR	Failed to write lock info
2022-03-04T14:01:20.708+0800	INFO	System platform x86_64_windows
2022-03-04T14:01:20.773+0800	WARN	Failed to get updating lock, skipping
2022-03-04T14:01:20.876+0800	WARN	Failed to get updating lock, skipping
2022-03-04T14:01:20.975+0800	WARN	Failed to get updating lock, skipping
2022-03-04T14:01:21.040+0800	INFO	Preparing inference environment
2022-03-04T14:01:21.041+0800	INFO	Inference environment is ready
2022-03-04T14:01:21.041+0800	INFO	Starting local cosy inference service
2022-03-04T14:01:21.053+0800	INFO	Local inference service initialized
2022-03-04T14:01:21.066+0800	ERROR	Failed to write lock info
2022-03-04T14:01:21.110+0800	INFO	Preparing inference environment
2022-03-04T14:01:21.111+0800	INFO	Inference environment is ready
2022-03-04T14:01:21.111+0800	INFO	Starting local cosy inference service
2022-03-04T14:01:21.160+0800	INFO	Local inference service initialized
2022-03-04T14:01:21.174+0800	ERROR	Failed to write lock info
2022-03-04T14:01:21.176+0800	INFO	Skip update, current version: 0.2.1
2022-03-04T14:01:21.176+0800	INFO	Succeed to update Cosy binary
2022-03-04T14:01:21.215+0800	INFO	Skip update model, current version: 0.0.3
2022-03-04T14:01:21.215+0800	INFO	Succeed to update Cosy model
2022-03-04T14:01:21.232+0800	INFO	Inference environment checked, skip downloading
2022-03-04T14:01:21.232+0800	INFO	Succeed to update inference env

**本地系统**
 - OS: Windows11
 - Cosy Version : Cloud Al Coding Assistant 0.10.1-alpha-20220302

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by zxdxjtu** [comment]
收到，感谢反馈，我们会尽快排查

**Comment by zxdxjtu** [comment]
请问能否提供下IDEA的日志方便我们排查，日志在IDEA上方工具栏的Help>Show log in Finder
![image](https://user-images.githubusercontent.com/9382205/156715710-6c3c291c-7687-4a86-b702-b24d3d1fe44d.png)

**Comment by ScmTble** [comment]
2022-03-04 15:09:55,042 [  23158]   INFO - pl.local.NativeFileWatcherImpl - Starting file watcher: D:\Program Files\JetBrains\IntelliJ IDEA 2020.3.2\bin\fsnotifier.exe 
2022-03-04 15:09:55,071 [  23187]   INFO - pl.local.NativeFileWatcherImpl - Native file watcher is operational. 
2022-03-04 15:09:55,086 [  23202]   INFO - tests.impl.DistributedTestHost - Host address=localhost/127.0.0.1 
2022-03-04 15:09:55,093 [  23209]   INFO - pi.vfs.impl.wsl.WslFileWatcher - WSL file watcher: D:\Program Files\JetBrains\IntelliJ IDEA 2020.3.2\bin\fsnotifier-wsl 
2022-03-04 15:09:55,153 [  23269]   INFO -                         STDOUT - Info  | RdCoroutineScope          | 19:JobScheduler FJ pool 6/11 | RdCoroutineHost overridden  
2022-03-04 15:09:55,161 [  23277]   WARN - l.NotificationGroupManagerImpl - Notification group CodeWithMe is already registered (group=com.intellij.notification.NotificationGroup@25ba4813). Plugin descriptor: PluginDescriptor(name=Code With Me, id=com.jetbrains.codeWithMe, descriptorPath=plugin.xml, path=D:\Program Files\JetBrains\IntelliJ IDEA 2020.3.2\plugins\cwm-plugin, version=213.6777.52, package=null, isBundled=true) 
2022-03-04 15:09:55,166 [  23282]   INFO - tellij.wsl.fs.WslContentLoader - fsd server found and will be used for WSL content loading 
2022-03-04 15:09:55,276 [  23392]   INFO - pl.projectlevelman.NewMappings - VCS Root: [Git] - [E:/LearnNote/java] 
2022-03-04 15:09:55,337 [  23453]   INFO - .intellij.openapi.wm.StatusBar - Factory is not registered as `com.intellij.statusBarWidgetFactory` extension: com.intellij.openapi.vcs.changes.committed.IncomingChangesIndicatorFactory 
2022-03-04 15:09:55,508 [  23624]   INFO - rojectCodeStyleSettingsManager - Initialized from default code style settings. 
2022-03-04 15:09:55,519 [  23635]   INFO - eStyle.CommonCodeStyleSettings - Loaded HTML common code style settings 
2022-03-04 15:09:55,519 [  23635]   INFO - eStyle.CommonCodeStyleSettings - Loaded Java common code style settings 
2022-03-04 15:09:55,519 [  23635]   INFO - eStyle.CommonCodeStyleSettings - Loaded XML common code style settings 
2022-03-04 15:09:55,525 [  23641]   INFO - el.ide.impl.WorkspaceModelImpl - Load workspace model from cache in 557 ms 
2022-03-04 15:09:55,568 [  23684]   INFO - ins.rd.platform.codeWithMe.z.a - sessionStatus: null 
2022-03-04 15:09:55,568 [  23684]   INFO - ins.rd.platform.codeWithMe.z.a - freeSessionRemainingTimeMs: null null 
2022-03-04 15:09:55,657 [  23773]   INFO -   #com.intellij.AbstractBundle - Cannot load resource bundle from *.properties file, falling back to slow class loading: messages.KotlinRunConfigurationsBundle 
2022-03-04 15:09:55,988 [  24104]   INFO - al.NewToolbarRootPaneExtension - Show old main toolbar: false; show old navigation bar: true 
2022-03-04 15:09:55,988 [  24104]   INFO - al.NewToolbarRootPaneExtension - Show new main toolbar: false 
2022-03-04 15:09:56,216 [  24332]   INFO - ij.cosy.ui.search.I18NConstant - Local language and country: zh_CN 
2022-03-04 15:09:56,216 [  24332]   INFO -   #com.intellij.AbstractBundle - Cannot load resource bundle from *.properties file, falling back to slow class loading: messageBundle 
2022-03-04 15:09:56,287 [  24403]   INFO - ntellij.cosy.common.CosyConfig - SYSTEM ARCH: arch=x86_64, os.arch=amd64, is32Bit=false 
2022-03-04 15:09:56,287 [  24403]   INFO - tellij.cosy.core.BinaryManager - checking cosy binary updating. 
2022-03-04 15:09:56,911 [  25027]   WARN - tellij.cosy.core.BinaryManager - local binary version is equal to plugin internal version, checking signature 
2022-03-04 15:09:57,118 [  25234]   INFO - plication.impl.ApplicationImpl - LONG VFS PROCESSING. Topic=BulkFileListener, offender=class com.intellij.psi.impl.file.impl.PsiVFSListener$1, message=after, time=90ms 
2022-03-04 15:09:57,133 [  25249]   INFO - ntellij.cosy.util.ProjectUtils - Start caching project java 
2022-03-04 15:09:57,154 [  25270]   INFO - ntellij.cosy.util.ProjectUtils - Start caching project java 
2022-03-04 15:09:57,415 [  25531]   INFO - tellij.cosy.core.BinaryManager - calculate Cosy binary signature. cost:91 
2022-03-04 15:09:57,481 [  25597]   INFO - tellij.cosy.core.BinaryUpdater - wait for updating 
2022-03-04 15:09:57,981 [  26097]   INFO -   #com.intellij.AbstractBundle - Cannot load resource bundle from *.properties file, falling back to slow class loading: copilot.copilot 
2022-03-04 15:09:58,079 [  26195]   INFO - tellij.cosy.core.BinaryUpdater - process output: 
2022-03-04 15:09:58,080 [  26196]   INFO - acloud.intellij.cosy.core.Cosy - starting cosy from C:\Users\ScmTble\.cosy 
2022-03-04 15:09:58,083 [  26199]   INFO - acloud.intellij.cosy.core.Cosy - .info not exist, start to create Cosy process 
2022-03-04 15:09:58,141 [  26257]   INFO - acloud.intellij.cosy.core.Cosy - starting cosy from C:\Users\ScmTble\.cosy 
2022-03-04 15:09:58,142 [  26258]   INFO - acloud.intellij.cosy.core.Cosy - .info file not exist, wait 100ms and retry 
2022-03-04 15:09:58,242 [  26358]   INFO - acloud.intellij.cosy.core.Cosy - Retry for fetching .info for 1 times, 9 times left 
2022-03-04 15:09:58,249 [  26365]   WARN - acloud.intellij.cosy.core.Cosy - Parsing .info file encountered Exception 
java.io.IOException: 另一个程序已锁定文件的一部分，进程无法访问。
	at java.base/java.io.FileInputStream.readBytes(Native Method)
	at java.base/java.io.FileInputStream.read(FileInputStream.java:279)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)
	at java.base/java.io.Reader.read(Reader.java:229)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1432)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1411)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1208)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1022)
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:2839)
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:2507)
	at com.alibabacloud.intellij.cosy.core.Cosy.checkInfoFile(Cosy.java:312)
	at com.alibabacloud.intellij.cosy.core.Cosy.readCosyInfoFile(Cosy.java:281)
	at com.alibabacloud.intellij.cosy.core.Cosy.connectCosyServer(Cosy.java:235)
	at com.alibabacloud.intellij.cosy.core.Cosy.startCosy(Cosy.java:226)
	at com.alibabacloud.intellij.cosy.core.Cosy.initCosyLanguageService(Cosy.java:210)
	at com.alibabacloud.intellij.cosy.core.Cosy.startup(Cosy.java:154)
	at com.alibabacloud.intellij.cosy.core.Cosy$1.run(Cosy.java:110)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:436)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:120)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:496)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-03-04 15:09:58,366 [  26482]   INFO - acloud.intellij.cosy.core.Cosy - Retry for fetching .info for 2 times, 8 times left 
2022-03-04 15:09:58,366 [  26482]   INFO - acloud.intellij.cosy.core.Cosy - .info file not exist, wait 100ms and retry 
2022-03-04 15:09:58,475 [  26591]   INFO - acloud.intellij.cosy.core.Cosy - Retry for fetching .info for 3 times, 7 times left 
2022-03-04 15:09:58,475 [  26591]   INFO - acloud.intellij.cosy.core.Cosy - .info file not exist, wait 100ms and retry 
2022-03-04 15:09:58,585 [  26701]   INFO - acloud.intellij.cosy.core.Cosy - Retry for fetching .info for 4 times, 6 times left 
2022-03-04 15:09:58,585 [  26701]   INFO - acloud.intellij.cosy.core.Cosy - .info file not exist, wait 100ms and retry 
2022-03-04 15:09:58,694 [  26810]   INFO - acloud.intellij.cosy.core.Cosy - Retry for fetching .info for 5 times, 5 times left 
2022-03-04 15:09:58,694 [  26810]   INFO - acloud.intellij.cosy.core.Cosy - .info file not exist, wait 100ms and retry 
2022-03-04 15:09:58,805 [  26921]   INFO - acloud.intellij.cosy.core.Cosy - Retry for fetching .info for 6 times, 4 times left 
2022-03-04 15:09:58,805 [  26921]   INFO - acloud.intellij.cosy.core.Cosy - .info file not exist, wait 100ms and retry 
2022-03-04 15:09:58,888 [  27004]   INFO -              PerformancePlugin - 性能插件处于静默模式 
2022-03-04 15:09:58,914 [  27030]   INFO - acloud.intellij.cosy.core.Cosy - Retry for fetching .info for 7 times, 3 times left 
2022-03-04 15:09:58,914 [  27030]   INFO - acloud.intellij.cosy.core.Cosy - .info file not exist, wait 100ms and retry 
2022-03-04 15:09:58,931 [  27047]   INFO - erver.followMe.FollowMeManager - Register new user 0:'ScmTble' with ClientId=ClientId(value=Host) 
2022-03-04 15:09:59,024 [  27140]   INFO - acloud.intellij.cosy.core.Cosy - Retry for fetching .info for 8 times, 2 times left 
2022-03-04 15:09:59,024 [  27140]   INFO - acloud.intellij.cosy.core.Cosy - .info file not exist, wait 100ms and retry 
2022-03-04 15:09:59,134 [  27250]   INFO - acloud.intellij.cosy.core.Cosy - Retry for fetching .info for 9 times, 1 times left 
2022-03-04 15:09:59,134 [  27250]   INFO - acloud.intellij.cosy.core.Cosy - .info file not exist, wait 100ms and retry 
2022-03-04 15:09:59,244 [  27360]   INFO - acloud.intellij.cosy.core.Cosy - Retry for fetching .info for 10 times, 0 times left 
2022-03-04 15:09:59,244 [  27360]   WARN - acloud.intellij.cosy.core.Cosy - Cannot read from .info, connect to Cosy server failed 
2022-03-04 15:09:59,244 [  27360]   WARN - acloud.intellij.cosy.core.Cosy - Cosy init failed 
2022-03-04 15:09:59,244 [  27360]   INFO - acloud.intellij.cosy.core.Cosy - succeed to startup cosy 
2022-03-04 15:09:59,537 [  27653]   INFO - ion.DelayedProjectSynchronizer - Workspace model loaded from cache. Syncing real project state into workspace model in 561 ms. Thread[JobScheduler FJ pool 3/11,4,main] 
2022-03-04 15:09:59,733 [  27849]   INFO -  #git4idea.commands.GitHandler - [.] git version 
2022-03-04 15:09:59,757 [  27873]   INFO - ij.psi.search.LogFileTypeIndex - Loading file type index snapshot 
2022-03-04 15:09:59,819 [  27935]   INFO - ge.ExternalProjectsDataStorage - Load external projects data in 43 millis (read time: 5) 
2022-03-04 15:09:59,866 [  27982]   INFO -  #git4idea.commands.GitHandler - git version 2.34.1.windows.1 
2022-03-04 15:09:59,887 [  28003]   INFO - ea.config.GitExecutableManager - Git version for D:\Program Files\PortableGit\bin\git.exe: 2.34.1.0 (MSYS) 
2022-03-04 15:09:59,901 [  28017]   WARN - ctionSystem.impl.ActionUpdater - 284 ms to grab EDT for ToggleUseSoftWrapsInPreviewAction#update (com.intellij.openapi.editor.actions.ToggleUseSoftWrapsInPreviewAction) 
2022-03-04 15:09:59,910 [  28026]   INFO - indexing.UnindexedFilesUpdater - Started indexing of java. Reason: On project open 
2022-03-04 15:09:59,920 [  28036]   INFO - indexing.UnindexedFilesUpdater - Performing delayed pushing properties tasks for java took 0ms; general responsiveness: ok; EDT responsiveness: ok 
2022-03-04 15:10:00,065 [  28181]   INFO - CompilerWorkspaceConfiguration - Available processors: 12 
2022-03-04 15:10:00,317 [  28433]   INFO - indexing.UnindexedFilesUpdater - Scanning of java uses 11 scanning threads 
2022-03-04 15:10:00,513 [  28629]   INFO - llij.database.util.SqlDialects - SQL dialects initialized in 0 ms 
2022-03-04 15:10:00,744 [  28860]   INFO - redIndexChunkConfigurationImpl - Chunk bundled-js-predefined-ffdd448c697d-e5421860d8a5-JavaScript-IU-213.6777.52 is registered for project 'java: matching: (fb=37, stub=86), incompatible: (fb=0, stub=0), unknown: (fb=9, stub=9),  
2022-03-04 15:10:01,854 [  29970]   INFO - j.compiler.server.BuildManager - BUILDER_PROCESS [stdout]: Build process started. Classpath: D:/Program Files/JetBrains/IntelliJ IDEA 2020.3.2/plugins/java/lib/jps-launcher.jar;D:/Program Files/Java/jdk1.8.0_281/lib/tools.jar 
2022-03-04 15:10:02,144 [  30260]   INFO - ntellij.cosy.util.ProjectUtils - Start caching project java 
2022-03-04 15:10:04,266 [  32382]   INFO - indexing.UnindexedFilesUpdater - Scanning completed for java. Number of scanned files: 46706; Number of files for indexing: 0 took 4340ms; general responsiveness: ok; EDT responsiveness: 1/4 sluggish, 1/4 very slow 
2022-03-04 15:10:04,270 [  32386]   INFO - indexing.UnindexedFilesUpdater - Finished for java. No files to index with loading content. 
2022-03-04 15:10:04,271 [  32387]   INFO - ij.psi.search.LogFileTypeIndex - File type index snapshot dropped 
2022-03-04 15:10:04,319 [  32435]   INFO - ntellij.cosy.util.ProjectUtils - Start caching project java 
2022-03-04 15:10:04,320 [  32436]   INFO - ntellij.cosy.util.ProjectUtils - Start caching project java 
2022-03-04 15:10:04,429 [  32545]   INFO - oudConfig.StatusBarInfoManager - === StatusBar.start create === 
2022-03-04 15:10:04,651 [  32767]   INFO - SharedIndexPostStartupActivity - Attached 1 pre-built shared indexes: bundled-js-predefined-ffdd448c697d-e5421860d8a5-JavaScript-IU-213.6777.52 
2022-03-04 15:10:05,697 [  33813]   INFO - j.ide.script.IdeStartupScripts - 0 startup script(s) found 
2022-03-04 15:10:05,791 [  33907]   INFO - gnostic.PerformanceWatcherImpl - Post-startup activities under progress took 6891ms; general responsiveness: ok; EDT responsiveness: 2/7 sluggish, 1/7 very slow 
2022-03-04 15:10:05,833 [  33949]   INFO - .services.SpaceKtsFileDetector - SpaceKtsFileDetector 
2022-03-04 15:10:05,939 [  34055]   INFO - tor.impl.FileEditorManagerImpl - Project opening took 11366 ms 
2022-03-04 15:10:06,719 [  34835]   INFO - System.impl.PopupMenuPreloader - Popup menu '编辑' preloaded at 'MainMenu' in 244 ms 
2022-03-04 15:10:06,803 [  34919]   INFO - System.impl.PopupMenuPreloader - Popup menu '文件' preloaded at 'MainMenu' in 337 ms 
2022-03-04 15:10:06,812 [  34928]   INFO - System.impl.PopupMenuPreloader - Popup menu '视图' preloaded at 'MainMenu' in 343 ms 
2022-03-04 15:10:06,956 [  35072]   INFO - System.impl.PopupMenuPreloader - Popup menu '导航' preloaded at 'MainMenu' in 487 ms 
2022-03-04 15:10:07,030 [  35146]   INFO - System.impl.PopupMenuPreloader - Popup menu '代码' preloaded at 'MainMenu' in 562 ms 
2022-03-04 15:10:07,049 [  35165]   INFO - System.impl.PopupMenuPreloader - Popup menu '构建' preloaded at 'MainMenu' in 580 ms 
2022-03-04 15:10:07,280 [  35396]   INFO - System.impl.PopupMenuPreloader - Popup menu '运行' preloaded at 'MainMenu' in 811 ms 
2022-03-04 15:10:07,360 [  35476]   INFO - System.impl.PopupMenuPreloader - Popup menu '工具' preloaded at 'MainMenu' in 891 ms 
2022-03-04 15:10:07,384 [  35500]   INFO - System.impl.PopupMenuPreloader - Popup menu '窗口' preloaded at 'MainMenu' in 915 ms 
2022-03-04 15:10:07,419 [  35535]   INFO - System.impl.PopupMenuPreloader - Popup menu '帮助' preloaded at 'MainMenu' in 949 ms 
2022-03-04 15:10:07,437 [  35553]   INFO - System.impl.PopupMenuPreloader - Popup menu '重构' preloaded at 'MainMenu' in 968 ms 
2022-03-04 15:10:07,592 [  35708]   INFO - .script.IdeScriptEngineManager - javax.script.ScriptEngineManager initialized in 285 ms 
2022-03-04 15:10:07,594 [  35710]   INFO - rationStore.ComponentStoreImpl - Registering unknown macros a.b.c in component DatabaseSettings 
2022-03-04 15:10:07,989 [  36105]   INFO - llij.cosy.ui.search.NewWelcome - official label font family is: javax.swing.plaf.FontUIResource[family=JetBrains Mono,name=JetBrains Mono,style=plain,size=15] 
2022-03-04 15:10:08,159 [  36275]   WARN - ctionSystem.impl.ActionUpdater - 209 ms to grab EDT for #update (com.intellij.openapi.wm.impl.ToolWindowHeader$1) 
2022-03-04 15:10:10,954 [  39070]   INFO - gnostic.WindowsDefenderChecker - Windows Defender status: not used 
2022-03-04 15:10:11,148 [  39264]   INFO - tellij.cosy.core.BinaryManager - checking cosy binary updating. 
2022-03-04 15:10:11,622 [  39738]   WARN - tellij.cosy.core.BinaryManager - local binary version is equal to plugin internal version, checking signature 
2022-03-04 15:10:11,786 [  39902]   INFO - m.codeWithMe.CodeWithMeCleanup - running activity to cleanup old thin clients... Root path is 'C:\Users\ScmTble\AppData\Local\JetBrains' 
2022-03-04 15:10:11,787 [  39903]   INFO - m.codeWithMe.CodeWithMeCleanup - found 0 Code With Me client system folders to check 
2022-03-04 15:10:11,787 [  39903]   INFO - m.codeWithMe.CodeWithMeCleanup - found 0 Code With Me client config folders to check 
2022-03-04 15:10:11,788 [  39904]   INFO - m.codeWithMe.CodeWithMeCleanup - keep only [] major versions 
2022-03-04 15:10:12,047 [  40163]   INFO - tellij.cosy.core.BinaryManager - calculate Cosy binary signature. cost:77 
2022-03-04 15:10:12,101 [  40217]   INFO - tellij.cosy.core.BinaryUpdater - wait for updating 
2022-03-04 15:10:12,677 [  40793]   INFO - tellij.cosy.core.BinaryUpdater - process output: 
2022-03-04 15:10:12,677 [  40793]   INFO - acloud.intellij.cosy.core.Cosy - starting cosy from C:\Users\ScmTble\.cosy 
2022-03-04 15:10:12,677 [  40793]   INFO - acloud.intellij.cosy.core.Cosy - .info not exist, start to create Cosy process 
2022-03-04 15:10:12,727 [  40843]   INFO - acloud.intellij.cosy.core.Cosy - starting cosy from C:\Users\ScmTble\.cosy 
2022-03-04 15:10:12,727 [  40843]   INFO - acloud.intellij.cosy.core.Cosy - .info file not exist, wait 100ms and retry 
2022-03-04 15:10:12,842 [  40958]   INFO - acloud.intellij.cosy.core.Cosy - Retry for fetching .info for 1 times, 9 times left 
2022-03-04 15:10:12,953 [  41069]   INFO - acloud.intellij.cosy.core.Cosy - Retry for fetching .info for 2 times, 8 times left 
2022-03-04 15:10:12,953 [  41069]   INFO - acloud.intellij.cosy.core.Cosy - .info file not exist, wait 100ms and retry 
2022-03-04 15:10:13,065 [  41181]   INFO - acloud.intellij.cosy.core.Cosy - Retry for fetching .info for 3 times, 7 times left 
2022-03-04 15:10:13,065 [  41181]   INFO - acloud.intellij.cosy.core.Cosy - .info file not exist, wait 100ms and retry 
2022-03-04 15:10:13,173 [  41289]   INFO - acloud.intellij.cosy.core.Cosy - Retry for fetching .info for 4 times, 6 times left 
2022-03-04 15:10:13,173 [  41289]   INFO - acloud.intellij.cosy.core.Cosy - .info file not exist, wait 100ms and retry 
2022-03-04 15:10:13,281 [  41397]   INFO - acloud.intellij.cosy.core.Cosy - Retry for fetching .info for 5 times, 5 times left 
2022-03-04 15:10:13,281 [  41397]   INFO - acloud.intellij.cosy.core.Cosy - .info file not exist, wait 100ms and retry 
2022-03-04 15:10:13,335 [  41451]   INFO - System.impl.PopupMenuPreloader - Popup menu '项目视图弹出窗口菜单' preloaded at 'ProjectViewPopup' in 189 ms 
2022-03-04 15:10:13,388 [  41504]   INFO - acloud.intellij.cosy.core.Cosy - Retry for fetching .info for 6 times, 4 times left 
2022-03-04 15:10:13,388 [  41504]   INFO - acloud.intellij.cosy.core.Cosy - .info file not exist, wait 100ms and retry 
2022-03-04 15:10:13,496 [  41612]   INFO - acloud.intellij.cosy.core.Cosy - Retry for fetching .info for 7 times, 3 times left 
2022-03-04 15:10:13,496 [  41612]   INFO - acloud.intellij.cosy.core.Cosy - .info file not exist, wait 100ms and retry 
2022-03-04 15:10:13,574 [  41690]   INFO - System.impl.PopupMenuPreloader - Popup menu '编辑器弹出窗口菜单' preloaded at 'EditorPopup' in 429 ms 
2022-03-04 15:10:13,605 [  41721]   INFO - acloud.intellij.cosy.core.Cosy - Retry for fetching .info for 8 times, 2 times left 
2022-03-04 15:10:13,605 [  41721]   INFO - acloud.intellij.cosy.core.Cosy - .info file not exist, wait 100ms and retry 
2022-03-04 15:10:13,718 [  41834]   INFO - acloud.intellij.cosy.core.Cosy - Retry for fetching .info for 9 times, 1 times left 
2022-03-04 15:10:13,718 [  41834]   INFO - acloud.intellij.cosy.core.Cosy - .info file not exist, wait 100ms and retry 
2022-03-04 15:10:13,824 [  41940]   INFO - acloud.intellij.cosy.core.Cosy - Retry for fetching .info for 10 times, 0 times left 
2022-03-04 15:10:13,824 [  41940]   WARN - acloud.intellij.cosy.core.Cosy - Cannot read from .info, connect to Cosy server failed 
2022-03-04 15:10:13,824 [  41940]   WARN - acloud.intellij.cosy.core.Cosy - Cosy init failed 
2022-03-04 15:10:13,825 [  41941]   INFO - acloud.intellij.cosy.core.Cosy - succeed to startup cosy 
2022-03-04 15:10:19,760 [  47876]   INFO - j.ide.actions.RevealFileAction - Exit code 1 
2022-03-04 15:10:21,159 [  49275]   INFO - rationStore.ComponentStoreImpl - Saving Project(name=java, containerState=COMPONENT_CREATED, componentStore=E:\LearnNote\java)RunManager took 39 ms

**Comment by zxdxjtu** [comment]
目前识别到是某些Windows系统特有的文件锁问题，正在努力修复中，为带来的不便深感抱歉

**Comment by ScmTble** [comment]
> 

好的，谢谢

**Comment by effynku** [comment]
亲爱的用户你好⁽⁽٩( ´͈ ᗨ `͈ )۶⁾⁾感谢你对Cosy的支持和反馈！上周五由你反馈的问题经过我们本周末的排查现在已经修复啦，点击链接下载最新版本即可正常使用：http://toolkit.aliyun.com/idea/cosy-intellij-0.10.1-alpha-20220304.zip
后续不管是遇到任何使用问题，或是有一些建议，都请随时联系我们～
