### ISSUE TITLE
Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.

### ISSUE THREAD

**Issue by sudo-keke** [alibaba-cloud-toolkit/cosy#69]
**每隔几分钟就报这个错**

**
java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.util.SlowOperations.assertSlowOperationsAreAllowed(SlowOperations.java:102)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:784)
	at com.intellij.psi.stubs.StubIndexImpl.processAllKeys(StubIndexImpl.java:442)
	at com.intellij.psi.impl.PsiShortNamesCacheImpl.processAllClassNames(PsiShortNamesCacheImpl.java:113)
	at com.intellij.psi.impl.CompositeShortNamesCache.processAllClassNames(CompositeShortNamesCache.java:101)
	at com.intellij.psi.impl.search.AllClassesSearchExecutor.lambda$processClassNames$4(AllClassesSearchExecutor.java:97)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$0(DumbService.java:113)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:144)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:113)
	at com.intellij.psi.impl.search.AllClassesSearchExecutor.processClassNames(AllClassesSearchExecutor.java:96)
	at com.alibabacloud.intellij.cosy.util.ProjectUtils.lambda$addProjectScopeClassesCache$2(ProjectUtils.java:137)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
**

**![image](https://user-images.githubusercontent.com/41411871/162231055-e73987d8-51b2-462a-99d4-44878713f986.png)**

**System（本地系统）**
 - OS: mac os
 - Cosy Version: IntelliJ IDEA 2021.3.1 (Ultimate Edition)

**Comment by zxdxjtu** [comment]
您好，这种情况一般出现在本机电脑性能比较吃紧的时候（比如内存较低），由于Cosy会调用IDEA内部的API，而当性能紧张时，IDEA内部会避免一些索引并且抛出这个异常提醒用户。我们近期也会去咨询下IDEA官方如何提前检测到这种性能异常，避免对内部API的调用。感谢反馈:)

**Comment by sudo-keke** [comment]
感谢回复
