### ISSUE TITLE
会导致idea卡死

### ISSUE THREAD

**Issue by javabcde** [alibaba-cloud-toolkit/cosy#80]
**Describe the bug（描述您遇到的问题）**
Caused by: java.lang.RuntimeException: unzip error:C:\Users\xxxx\AppData\Local\Temp\cosy_1650952985503.zip
Caused by: java.io.FileNotFoundException: C:\Users\xxxx\.cosy\bin\0.2.6\x86_64_windows\cosylocal.exe (另一个程序正在使用此文件，进程无法访问。)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:2451)
	at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:2415)
	at org.apache.commons.io.FileUtils.copyToFile(FileUtils.java:1042)
	at com.alibabacloud.intellij.cosy.util.ZipUtil.unZip(ZipUtil.java:78)
	... 24 more
2022-04-26 14:22:12,953 [   3872]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2021.3.3  Build #IU-213.7172.25 
2022-04-26 14:22:12,954 [   3873]  ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.14.1; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 

idea升级之后 会导致idea卡死 卡在第一屏  必须把对应的zip删除才可以使用idea 或者多次点击idea才可以重新进入

**Comment by zxdxjtu** [comment]
请问下你的IDEA版本是什么？
方便把idea的日志发我们一下吗？在上边工具栏的Help>Show log in Finder。
一种可能是原来的Cosy进程没有kill掉，导致解压时无法覆盖。临时解决方案时手动把cosy进程kill，删除C盘用户目录下的.cosy目录，然后打开IDEA。
如果能够提供我们日志和版本信息的话，我们能更准确的定位和修复，感谢

**Comment by javabcde** [comment]
从2020.3升级到2021.3
[idea.log](https://github.com/alibaba-cloud-toolkit/cosy/files/8560517/idea.log)


> 请问下你的IDEA版本是什么？ 方便把idea的日志发我们一下吗？在上边工具栏的Help>Show log in Finder。 一种可能是原来的Cosy进程没有kill掉，导致解压时无法覆盖。临时解决方案时手动把cosy进程kill，删除C盘用户目录下的.cosy目录，然后打开IDEA。 如果能够提供我们日志和版本信息的话，我们能更准确的定位和修复，感谢

**Comment by zxdxjtu** [comment]
看报错是文件正在使用无法覆盖。你可以先把IDEA关闭，然后在进程里看看有没有cosy和cosylocal的进程，然后把他们杀掉，理论上把cosy进程杀掉，cosylocal也会随之关闭。然后删除.cosy目录，再打开IDEA。

**Comment by javabcde** [comment]
> 看报错是文件正在使用无法覆盖。你可以先把IDEA关闭，然后在进程里看看有没有cosy和cosylocal的进程，然后把他们杀掉，理论上把cosy进程杀掉，cosylocal也会随之关闭。然后删除.cosy目录，再打开IDEA。

貌似是idea2021.3退出的时候 图里面的这两个进程不会跟着一起退出 导致再次启动idea 就开始卡住了 每次退出了必须手动删除这俩进程才行
![1651023271(1)](https://user-images.githubusercontent.com/23007542/165420709-b7e1c625-a2ee-456e-aeca-d1bb2d236382.jpg)

**Comment by zxdxjtu** [comment]
嗯嗯，看起来是我们的kill进程失败了，导致解压时文件被占用。我们继续排查下kill进程失败的原因，同时我也会在这周给您打个热修包，通过一些版本检查机制，避免过于频繁的同版本覆盖。
方便的话，可以加一下钉钉内测群：邀请你加入钉钉群聊阿里云智能编码插件内测用户群，点击进入查看详情 https://h5.dingtalk.com/circle/healthCheckin.html?dtaction=os&corpId=ding95a43ae0c7b0fc32507795ee3a72e564&04043=11758&cbdbhh=qwertyuiop

**Comment by zxdxjtu** [comment]
您好，我们做了下热修处理，尽量避免了二进制覆盖操作，并且做了些杀进程的容错，麻烦本地安装看看是否能解决你的问题：https://codeup-algo.oss-cn-hangzhou.aliyuncs.com/biz/cosy-intellij/hotfix/cosy-intellij-0.10.2-beta-unzip-error-fix.zip

**Comment by javabcde** [comment]
> 您好，我们做了下热修处理，尽量避免了二进制覆盖操作，并且做了些杀进程的容错，麻烦本地安装看看是否能解决你的问题：https://codeup-algo.oss-cn-hangzhou.aliyuncs.com/biz/cosy-intellij/hotfix/cosy-intellij-0.10.2-beta-unzip-error-fix.zip

目前来看好像是可以了 谢谢

**Comment by zxdxjtu** [comment]
感谢反馈。issue先关啦，这个修复也会在下个版本中发布。
