### ISSUE TITLE
idea exception messages

### ISSUE THREAD

**Issue by jiaweihuang2022** [alibaba-cloud-toolkit/cosy#81]
**Describe the bug（描述您遇到的问题）**
idea internal  errors

**To Reproduce（复现步骤）**
when i open the idea 

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/104067019/165725459-7d55c859-ad85-46ef-8c49-7f967f1813b2.png)

com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl #JAVA  because: containing file is null; hierarchy=class com.intellij.psi.impl.source.PsiTypeElementImpl, class com.intellij.psi.impl.source.PsiParameterImpl, context=null, contextFile=null
invalidated at: see attachment; Type element reference of class com.intellij.psi.impl.source.PsiParameterImpl #PsiParameterImpl, index=0, invalid; augmenters=[com.intellij.psi.impl.source.JShellPsiAugmentProvider@32ec0c2c, com.intellij.psi.impl.RecordAugmentProvider@3c1874de, de.plushnikov.intellij.plugin.provider.LombokAugmentProvider@17e36cd5]
	at com.intellij.psi.impl.source.PsiClassReferenceType.resolveGenerics(PsiClassReferenceType.java:175)
	at com.intellij.psi.impl.source.PsiClassReferenceType.resolve(PsiClassReferenceType.java:121)
	at com.intellij.psi.util.PsiTypesUtil.getPsiClass(PsiTypesUtil.java:146)
	at com.alibabacloud.intellij.cosy.linguist.psi.model.CosyPsiJavaCodeReferenceElement.guessVariable(CosyPsiJavaCodeReferenceElement.java:148)
	at com.alibabacloud.intellij.cosy.linguist.psi.model.CosyPsiJavaCodeReferenceElement.parse(CosyPsiJavaCodeReferenceElement.java:122)
	at com.alibabacloud.intellij.cosy.linguist.psi.core.CosyPsiManager.guessCosyPsiElement(CosyPsiManager.java:85)
	at com.alibabacloud.intellij.cosy.linguist.psi.core.CosyPsiManager.convertToCosyPsiElement(CosyPsiManager.java:59)
	at com.alibabacloud.intellij.cosy.linguist.processor.CandidateAnalyzeProcessor$CosyRootComputer.lambda$convertCosyTreeWithTimeout$0(CandidateAnalyzeProcessor.java:224)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:920)
	at com.alibabacloud.intellij.cosy.linguist.processor.CandidateAnalyzeProcessor$CosyRootComputer.lambda$convertCosyTreeWithTimeout$1(CandidateAnalyzeProcessor.java:222)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:326)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by zxdxjtu** [comment]
您好，该问题已经识别到并且修复，会随着下个版本一起发布。这个问题不影响功能，只是IDEA内部API的一个异常，麻烦先忽略下

**Comment by jiaweihuang2022** [comment]
thanks for your reply
