### ISSUE TITLE
idea里每次启动报错

### ISSUE THREAD

**Issue by ShaddockCyan** [alibaba-cloud-toolkit/cosy#94]
**Describe the bug（描述您遇到的问题）**
后台报错

**To Reproduce（复现步骤）**
每次启动idea打开项目都会报错一次

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/55221547/170476796-7d098a4f-f349-49ce-9005-ff4a39ac9085.png)
java.util.concurrent.CompletionException: java.lang.RuntimeException: unzip error:C:\Users\SHADDO~1\AppData\Local\Temp\cosy_1653563156669.zip
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1742)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.RuntimeException: unzip error:C:\Users\SHADDO~1\AppData\Local\Temp\cosy_1653563156669.zip
	at com.alibabacloud.intellij.cosy.util.ZipUtil.unZip(ZipUtil.java:83)
	at com.alibabacloud.intellij.cosy.core.BinaryManager.initBinary(BinaryManager.java:111)
	at com.alibabacloud.intellij.cosy.core.BinaryManager.checkBinary(BinaryManager.java:90)
	at com.alibabacloud.intellij.cosy.core.BinaryManager.checkBinary(BinaryManager.java:57)
	at com.alibabacloud.intellij.cosy.CosyLoader.appStarting(CosyLoader.java:43)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:645)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:624)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:390)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:179)
	at com.sun.proxy.$Proxy40.appStarting(Unknown Source)
	at com.intellij.idea.IdeStarter.openProjectIfNeeded(IdeStarter.kt:136)
	at com.intellij.idea.IdeStarter.main(IdeStarter.kt:80)
	at com.intellij.idea.ApplicationLoader$startApp$3.run(ApplicationLoader.kt:190)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
	... 8 more
Caused by: java.io.FileNotFoundException: C:\Users\ShaddockCyan\.cosy\bin\0.2.6\x86_64_windows\cosylocal.exe (另一个程序正在使用此文件，进程无法访问。)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:2451)
	at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:2415)
	at org.apache.commons.io.FileUtils.copyToFile(FileUtils.java:1042)
	at com.alibabacloud.intellij.cosy.util.ZipUtil.unZip(ZipUtil.java:78)
	... 24 more

**System（本地系统）**
 - OS: win11正式版
 - Cosy Version: 0.10.2beta

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by zxdxjtu** [comment]
您好，我们对这个问题做了修复，可以使用下我们的内测版本：

1⃣️网络顺畅环境直接配置channel在插件市场下载：
点击Preferences -> Plugins -> Settings Icon -> Manage Plugin Repositories, 添加：https://plugins.jetbrains.com/plugins/alpha/list ，在插件市场搜索框内输入【Alibaba Cloud AI Coding Assistant】或者【Cosy】，确认为0.10.3-alpha-20220520版本后即可开始体验～
2⃣️离线包请点击直接下载：http://toolkit.aliyun.com/idea/cosy-intellij-0.10.3-alpha-20220520.zip

遇到这样的问题，也可以尝试，把cosy进程杀死，然后删除~/.cosy目录，然后重启下IDEA

**Comment by zxdxjtu** [comment]
您好，最新的0.10.3-beta版本已发布，包括了上述的内测版修复，欢迎更新
