### ISSUE TITLE
每天几个错误

### ISSUE THREAD

**Issue by pengtang1024** [alibaba-cloud-toolkit/cosy#96]
**Describe the bug（描述您遇到的问题）**
![image](https://user-images.githubusercontent.com/24929756/172550863-31c4e090-9881-4ff8-9574-8421ad958416.png)

**To Reproduce（复现步骤）**

**Screenshots（截图）**
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.intellij.openapi.project.DumbService because container is already disposed (container=Project(name=temple-fair, containerState=DISPOSE_COMPLETED, componentStore=D:\Work\IdeaProjects\temple-fair) (disposed))
	at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:34)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:632)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:584)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.intellij.openapi.project.DumbService.getInstance(DumbService.java:199)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:105)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readOrBuild(StubTreeLoaderImpl.java:49)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:634)
	at com.intellij.psi.impl.source.PsiFileImpl.getGreenStubTree(PsiFileImpl.java:956)
	at com.intellij.psi.impl.source.SpineRef.getGreenStub(SpineRef.java:39)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getGreenStub(StubBasedPsiElementBase.java:352)
	at com.intellij.psi.impl.source.PsiClassImpl.getQualifiedName(PsiClassImpl.java:149)
	at com.alibabacloud.intellij.cosy.linguist.psi.model.CosyPsiJavaCodeReferenceElement.tacklePsiClass(CosyPsiJavaCodeReferenceElement.java:203)
	at com.alibabacloud.intellij.cosy.linguist.psi.model.CosyPsiJavaCodeReferenceElement.guessClass(CosyPsiJavaCodeReferenceElement.java:164)
	at com.alibabacloud.intellij.cosy.linguist.psi.model.CosyPsiJavaCodeReferenceElement.parse(CosyPsiJavaCodeReferenceElement.java:120)
	at com.alibabacloud.intellij.cosy.linguist.psi.core.CosyPsiManager.guessCosyPsiElement(CosyPsiManager.java:85)
	at com.alibabacloud.intellij.cosy.linguist.psi.core.CosyPsiManager.convertToCosyPsiElement(CosyPsiManager.java:59)
	at com.alibabacloud.intellij.cosy.linguist.processor.CandidateAnalyzeProcessor$CosyRootComputer.lambda$convertCosyTreeWithTimeout$0(CandidateAnalyzeProcessor.java:224)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:920)
	at com.alibabacloud.intellij.cosy.linguist.processor.CandidateAnalyzeProcessor$CosyRootComputer.lambda$convertCosyTreeWithTimeout$1(CandidateAnalyzeProcessor.java:222)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:326)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

**System（本地系统）**
 - OS: 
 - Cosy Version: 

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by zxdxjtu** [comment]
非常抱歉影响了你的开发体验，这个问题是由于我们做了一些IDEA API内部调用，当IDEA窗口关闭、分支切换等操作发生时，插件的调用还没停止导致的，对功能没有影响，但是由于IDEA会把错误抛出，对用户打扰比较大。
我们已经做了大量的这类问题避免，但由于调用区域过多，有一些遗漏，感谢这次的问题反馈，我们已经做了修复，会在下个版本发布:)

**Comment by zxdxjtu** [comment]
您好，该报错已经在最新的0.10.3-beta版本修复，欢迎更新。
由于我们对IDEA内部PSI API调用比较多，很难完全制止这些无用的报错信息透出给用户，如果再次看到类似的报错，欢迎指给我们，我们会尽量在下个版本修复上线。
